### ISSUE TITLE
Twitch exception - Failed to get next part of the stream

### ISSUE THREAD

**Issue by LXGaming** [sedmelluq/lavaplayer#100]
Attempting to play a twitch.tv stream results in the following error: https://gist.github.com/LXGaming/5843473ec930331364b28f3c88c0f1c2

Dependencies:
 - JDA v3.5.1_346
 - LavaPlayer v1.2.56

**Comment by sedmelluq** [comment]
Fixed as of `1.2.58`.

**Comment by LXGaming** [comment]
Thank you for fixing this.
