### ISSUE TITLE
Some public playlists fail to load (detected as private)

### ISSUE THREAD

**Issue by joe27g** [sedmelluq/lavaplayer#103]
Playlists that were created anonymously, such as https://www.youtube.com/playlist?list=TLGGjDWAo9Avs30yNTAzMjAxOA, fail to load and throw `The playlist is private.`

The playlist is public; however, it is missing some info. I'm assuming it has to do with `document.select("#pl-header")` in [YoutubeAudioSourceManager](https://github.com/sedmelluq/lavaplayer/blob/34dc1acb9c0aff3b690a6341b46f551b83dc39ab/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioSourceManager.java#L418), but I couldn't really figure out how this worked or why it would yield different results for anonymous playlists.

**Comment by CAC27** [comment]
Edit: Doesn't happen only with anonymous playlists. Perhaps it's new playlists or something. https://www.youtube.com/playlist?list=PLC1og_v3eb4jJtActnUFBXYrTbr7oF6N- also does not work.

**Comment by sedmelluq** [comment]
I can't test the first one as it doesn't exist anymore, and the second one works fine for me.

**Comment by joe27g** [comment]
Sorry about the lack of details here. I just tested it again, same result as before. (using v1.2.58)
![image](https://user-images.githubusercontent.com/20873239/38644278-9bcc4814-3da5-11e8-9cdc-519c6f68bd47.png)
That's the result I get from playing the second playlist. The anonymous playlists seem to work now though. (for future reference, those can be generated with a link like [this](https://www.youtube.com/watch_videos?video_ids=A_MjCqQoLLA,Bl4dEAtxo0M,XGVNE8nNzPY,qOfkpu6749w,jniYhg8il_c,m2uTFF_3MaA,Vq25ZJwZJzU,eFjjO_lhf9c,Lo2qQmj0_h4,X2ZF9IuHlB0) which redirects to an actual playlist with ID.)

**Comment by joe27g** [comment]
Correction: both seem to be fixed after I updated to v1.2.58. Apparently I had a separate issue that made the wrong string get passed to the player for some playlists
