### ISSUE TITLE
Tracks with undefined duration not ending.

### ISSUE THREAD

**Issue by Moocow9m** [sedmelluq/lavaplayer#105]
If a track playing has the duration as Long.MAX_VALUE, the track will not end(at least in all(43) of my tests), and the next track will not be played. Any way to figure out if a track is in this state and continue with queue? The files are ogg with opus encoding(It plays it well). May be related to #34

**Comment by sedmelluq** [comment]
Could you provide a sample file?

**Comment by Moocow9m** [comment]
@sedmelluq Here is one of the files used: https://www.dropbox.com/s/rz2oim2rnnqel7y/%E3%80%90Flowerfell%E3%80%91%20Secret%20Garden%20%E3%80%90Original%20Song%E3%80%91.opus?dl=0

**Comment by sedmelluq** [comment]
Unable to reproduce, the end event is sent just fine for me. As for duration, will add it soon (along with metadata if present), but seeking is a bit more complex.
