### ISSUE TITLE
SoundCloud Streaming does not work on Linux.

### ISSUE THREAD

**Issue by zimsneexh** [sedmelluq/lavaplayer#110]
It works in IntellIJ and as a standalone Jar in Windows. Does not work on Linux, YouTube support does.

**Comment by Frederikam** [comment]
Unable to repro on Ubuntu Server. Please provide more details 
![image](https://user-images.githubusercontent.com/2582617/39088725-6403927e-45b7-11e8-9937-aae4bf081b8e.png)

**Comment by Frederikam** [comment]
I'm not sure what you mean when you say that you "get no output" and your "queue is still empty". What happens to your `AudioLoadResultHandler`?

**Comment by 21Joakim** [comment]
I had a problem with streaming from soundcloud (and twitch I think) when I had forgot to give the bot write permissions though it did throw errors if I am not mistaken, try to run it with sudo if you aren't already doing that (Given that you have such access to the server)

**Comment by gabixdev** [comment]
Do you host on OVH? Check you can reach soundcloud.

```
curl -I https://soundcloud.com
```

**Comment by shikhir-arora** [comment]
I have two OVH dedicated servers (US West Coast and Canada), no issues here. I'm using Lavalink, but it uses Lavaplayer the same.

**Comment by gabixdev** [comment]
Yep, but only France is banned from SoundCloud

**Comment by stefan-reich** [comment]
> Yep, but only France DCs are banned from SoundCloud

What are DCs? And who banned them?

**Comment by MCOfficer** [comment]
> 
> 
> > Yep, but only France DCs are banned from SoundCloud
> 
> What are DCs? And who banned them?

DC = datacenter. see [this forum post](https://community.soundcloud.com/desktop-230066/access-from-ovh-ip-to-soundcloud-results-in-http-error-403-6871592#post16509849) for more details
