### ISSUE TITLE
Audio shutters (only when not active on teamviewer)

### ISSUE THREAD

**Issue by UnderKoen** [sedmelluq/lavaplayer#111]
When I'm active on teamviewer the audio is clear but the moment i close it it's begins to shuttering.

**Comment by UnderKoen** [comment]
I hosting my bot with discord4j on a server, which i can acces with teamviewer the moment i connect to the server it is clear audio but when i disconnect it is shuttering. My audio code of my bot: https://github.com/UnderKoen/UnderBot/blob/master/discordbot/src/main/java/nl/underkoen/discordbot/music/MusicHandler.java

**Comment by Repulser** [comment]
I recommend staying connected to teamviewer
