### ISSUE TITLE
Error: Thread [main] (Suspended (exception NoSuchMethodError))

### ISSUE THREAD

**Issue by EthanBuckton** [sedmelluq/lavaplayer#115]
When launching, it gives me the error: Thread [main] (Suspended (exception NoSuchMethodError))
Then it links me to 
`` try {
      for (String line : IOUtils.readLines(listFileStream, StandardCharsets.UTF_8)) {
        String fileName = line.trim();
        if (!fileName.isEmpty()) {
          addFromResourceFile(basePath + "/" + fileName);
        }
      }
    } finally {
      IOUtils.closeQuietly(listFileStream);
    }``

**Comment by natanbc** [comment]
NoSuchMethodError indicates a needed method was not found at runtime. This is usually caused by outdated dependencies at runtime. Also, could you post the full stacktrace?

**Comment by sedmelluq** [comment]
Indeed, this seems like an outdated commons-io package. This generally happens if you use Maven. A fix would be to manually specify the dependency with the latest version in your `pom.xml`. This is the relevant package: http://search.maven.org/#artifactdetails%7Ccommons-io%7Ccommons-io%7C2.6%7Cjar

**Comment by EthanBuckton** [comment]
Thank both of you for your help. I managed to get it to work (thanks to the link @sedmelluq sent me). You've both been a massive help, and I can't thank you enough.
