### ISSUE TITLE
High CPU Usage on RPi3

### ISSUE THREAD

**Issue by JakeStanger** [sedmelluq/lavaplayer#12]
When streaming a video from YouTube, HTOP reports CPU usage of 100% and the sound playback stutters. A Raspberry Pi 3 should easily be able to stream and process audio; prior to using LavaPlayer I was using JDA's old built-in system on a RPi 1A without an issue.

Is there anything I can do to reduce CPU usage, otherwise I believe this should be considered an issue worth looking into?

It is perhaps also worth noting that on my desktop PC the application is reported as using 0% CPU; perhaps the network IO is straining the Pi?

**Comment by JakeStanger** [comment]
I switched from OpenJDK to Oracle JDK and the issue appears to go away - I guess the OpenJDK's floating point support is too weak to handle audio streaming

**Comment by Frederikam** [comment]
Oracle java is known to be better optimized for ARM.

**Comment by JakeStanger** [comment]
Thanks for the tip, I'll remember that for the future.
