### ISSUE TITLE
Maven import giving "ArrayIndexOutOfBoundsException"

### ISSUE THREAD

**Issue by Emperor-Koala** [sedmelluq/lavaplayer#122]
I tried importing this into my maven project, and for some reason it returns "21626 java.lang.ArrayIndexOutOfBoundsException: ..."

I am not sure if this is just me being stupid or if this is an error

**Comment by Emperor-Koala** [comment]
I am using Eclipse Oxygen 3 as my IDE, and the error is read as line 1 of my pom.xml file.

pom.xml: https://pastebin.com/XGAFWpRL

Stacktrace: https://pastebin.com/8t7gbu2R

**Comment by napstr** [comment]
This looks like an error of Eclipse, imo. You could try running something like `mvn install` from the command line just to be sure that it's not maven.

**Comment by Emperor-Koala** [comment]
I don't know what the problem was, but using a different computer, it works perfectly now. No idea what was wrong with it.
