### ISSUE TITLE
No Sound when Bot gets kicked on other Guild (using JDA 3)

### ISSUE THREAD

**Issue by dp-t-rex** [sedmelluq/lavaplayer#13]
I have my test bot connected to two guilds. When i kick it of one guild the player will "stop" playing in the other guild. It is not really stopping the song, but not making any sound, like it was muted. By pausing and unpausing the bot again i can hear sound again. Is there anything i can do against that?
(My lavaplayer and the jda are up-to-date).

Thank you. 😃

**Comment by NachtRaben** [comment]
I am actually noticing this behavior also.
Guild1: Playing song.
Guild2: Playing different song.
Execute "stop" in guild 1.
(this calls the AudioPlayers stopTrack() and clears the queue for that guild)
Guild1: Will stop playing the song and call its TrackStopEvent
Guild2: Will just become perpetually quiet until the next track starts or it is paused, unpaused.

Code is mostly based on the examples provided in this repo, only minor changes made.

**Comment by sedmelluq** [comment]
Disord bug: https://trello.com/c/fVzj57Pa/181-bot-disconnecting-from-an-audio-server-in-mutual-guild-stops-playback-in-current-voicechannel

**Comment by dp-t-rex** [comment]
@sedmelluq Did they say anything about fixing it?

**Comment by sedmelluq** [comment]
I haven't personally discussed this with Discord developers. From what I can tell from that link is that it's not a very high priority issue for them.
