### ISSUE TITLE
REST API: Extremely slow response time on Youtube MIX playlists.

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [sedmelluq/lavaplayer#130]
_This is a copy of https://github.com/Frederikam/Lavalink/issues/141._

Youtube can make temporary playlists called mixes for the user. The difference between these and normal playlists is that the videos aren't numbered and once all 50 are watched another 50 get added (plus they exist temporary). For the Youtube API, these should behave just like a normal playlist. But for some reason I had Lavalinks REST API take 20 seconds to perform a request to a Youtube mix.
This is not happening under load but happens consistently.

These are response times I collected with Postman:
https://sharex.reinfernhout.xyz/i/20ufF.png

When testing with the Youtube API I found no longer response times for Youtube mixes myself.

**Comment by sedmelluq** [comment]
The mix page does not provide enough info for each track it contains, thus a request for each track must be made separately. If YouTube API was supported, then one possible configurable option would be to use API only for mixes, to minimize the usage of the API key to only the cases where it significantly improves performance.

**Comment by sedmelluq** [comment]
Mix loading has been improved to not make additional requests.
