### ISSUE TITLE
Can you release .jar file?

### ISSUE THREAD

**Issue by istanbuls** [sedmelluq/lavaplayer#138]
Is it possible to provide *.jar file(s)?

**Comment by Frederikam** [comment]
Jars are provided via Bintray https://bintray.com/sedmelluq/com.sedmelluq/download_file?file_path=com%2Fsedmelluq%2Flavaplayer%2F1.3.9%2Flavaplayer-1.3.9.jar

**Comment by sedmelluq** [comment]
As mentioned above, individual JARs without embedded dependencies can be found on Bintray, but using those directly is not recommended, as it takes a lot of work to set the dependencies up correctly, plus any change may make it explode again.

There will NOT be a jar with dependencies.
