### ISSUE TITLE
Can't listen audio stream from icecast server

### ISSUE THREAD

**Issue by FlashOnFire** [sedmelluq/lavaplayer#139]
Hi. I'm using icecast to stream audio. I'm trying to create a bot to listen to this audio stream but i can't make it working. It's a normal http audio stream.... Can someone help me ?

**Comment by FlashOnFire** [comment]
I'm getting no match

**Comment by MCOfficer** [comment]
putting aside the fact that the issues might not be the correct place to ask, can you post some more details? what's your code at the moment? can you provide an example URL? etc. etc.

**Comment by FlashOnFire** [comment]
Oh sorry, I missed to give the code.

File DiscordMusicManager.java :

`package fr.flashonfire.ldradiobotserver.music.discord;

import com.sedmelluq.discord.lavaplayer.player.AudioLoadResultHandler;
import com.sedmelluq.discord.lavaplayer.player.AudioPlayerManager;
import com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager;
import com.sedmelluq.discord.lavaplayer.source.AudioSourceManagers;
import com.sedmelluq.discord.lavaplayer.tools.FriendlyException;
import com.sedmelluq.discord.lavaplayer.track.AudioPlaylist;
import com.sedmelluq.discord.lavaplayer.track.AudioTrack;

import fr.flashonfire.ldradiobotserver.music.discord.objects.DiscordMusicPlayer;

public class DiscordMusicManager {

	private final static AudioPlayerManager manager = new DefaultAudioPlayerManager();
	private final static DiscordMusicPlayer player = new DiscordMusicPlayer(manager.createPlayer());

	public DiscordMusicManager() {
		AudioSourceManagers.registerRemoteSources(manager);
		AudioSourceManagers.registerLocalSource(manager);
	}

	public synchronized static DiscordMusicPlayer getPlayer() {
		return player;
	}

	public static void addSource(String source) {
		manager.loadItemOrdered(player, source, new DiscordMusicManager.AudioLoad());
	}

	private static class AudioLoad implements AudioLoadResultHandler {

		@Override
		public void trackLoaded(AudioTrack audioTrack) {
			System.out.println("loaded");
			DiscordMusicManager.getPlayer().playTrack(audioTrack);
		}

		@Override
		public void playlistLoaded(AudioPlaylist audioPlaylist) {
		}

		@Override
		public void noMatches() {
			System.out.println("nomatch");
		}

		@Override
		public void loadFailed(FriendlyException e) {
			System.err.println("Impossible de jouer la piste (raison: " + e.getMessage() + ")");
		}
	}
}
`
File DiscordMusicPlayer.java :
`package fr.flashonfire.ldradiobotserver.music.discord.objects;

import com.sedmelluq.discord.lavaplayer.player.AudioPlayer;
import com.sedmelluq.discord.lavaplayer.track.AudioTrack;

public class DiscordMusicPlayer {
	private final AudioPlayer audioPlayer;

	public DiscordMusicPlayer(AudioPlayer audioPlayer) {
		this.audioPlayer = audioPlayer;
	}

	public AudioPlayer getAudioPlayer() {
		return audioPlayer;
	}

	public AudioPlayerSendHandler getAudioSendHandler() {
		return new AudioPlayerSendHandler(audioPlayer);
	}

	public synchronized void playTrack(AudioTrack track) {
		audioPlayer.startTrack(track, false);
	}
}

`

File AudioPlayerSendHandler.java :

`package fr.flashonfire.ldradiobotserver.music.discord.objects;

import com.sedmelluq.discord.lavaplayer.player.AudioPlayer;
import com.sedmelluq.discord.lavaplayer.track.AudioTrack;

public class DiscordMusicPlayer {
	private final AudioPlayer audioPlayer;

	public DiscordMusicPlayer(AudioPlayer audioPlayer) {
		this.audioPlayer = audioPlayer;
	}

	public AudioPlayer getAudioPlayer() {
		return audioPlayer;
	}

	public AudioPlayerSendHandler getAudioSendHandler() {
		return new AudioPlayerSendHandler(audioPlayer);
	}

	public synchronized void playTrack(AudioTrack track) {
		audioPlayer.startTrack(track, false);
	}
}
`

**Comment by FlashOnFire** [comment]
I can't let the audio stream running now. I have to go, sorry

**Comment by FlashOnFire** [comment]
My browser can listen to the stream on this url. But when i use the same url with lavaplayer, I'm getting no match.

**Comment by FlashOnFire** [comment]
Oh, I found my error. I wasn't calling the constructor at any time so the sources weren't registered....
Anyway, thank you for your help ! :wink:
