### ISSUE TITLE
Constantly receiving FriendlyException "Something went wrong when looking up the track"

### ISSUE THREAD

**Issue by kryspy** [sedmelluq/lavaplayer#14]
Don't know if this is temporary, but this exception keeps on repeating itself. At first I thought it was my code going wrong, however I tested using your example and it appears that it errored anyways (even though a couple of hours ago it was working perfectly)

**Comment by sedmelluq** [comment]
Get the full stack trace (including the part after "Caused by").

**Comment by kryspy** [comment]
There was no stack trace in the console. It only showed up when using the PlayerManager's loadFailed method.

**Comment by sedmelluq** [comment]
You can either:
* Print the exception you get as an argument in `loadFailed` manually.
* Add logback as a dependency so that the logs aren't ignored.
