### ISSUE TITLE
Metadata from opus file starts with "="

### ISSUE THREAD

**Issue by Bleuzen** [sedmelluq/lavaplayer#140]
Hi, I have an AudioTrack and get some metadata from it, for example the title:

```
AudioTrack track = ...;
-> track.getInfo().title;
```

With MP3 files it works, but when loading .opus files, the metadata always starts with "=".
So for example song name is "Hass", lavaplayer outputs "=Hass" as title.

**Comment by sedmelluq** [comment]
Fixed during refactoring.
