### ISSUE TITLE
Tags not read from ogg audio files

### ISSUE THREAD

**Issue by Bleuzen** [sedmelluq/lavaplayer#141]
I try to read the tags from ogg files.
`AudioTrack.getInfo().title` for example outputs "Unknown title" but the audio file has this tag.
Also `AudioTrack.getInfo().author` does output "Unknown artist" but the files has an artist tag.

**Comment by napstr** [comment]
Can you upload such an example file?

**Comment by Bleuzen** [comment]
@napstr Here is a preview of one of my upcomming songs as ogg:
https://mega.nz/#!xcUV0Y4a!U7vCn2RJZR8QamgA0aBS6-G0O_LFM2yrjUluj9BNsXA

It has tags (artist, title and year) but lavaplayer don't get them.

**Comment by napstr** [comment]
This is a vorbis encoded file, and for ogg vorbis files reading the metadata appears to not be implemented (see https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/container/ogg/OggVorbisTrackProvider.java#L59).
I'm sure a contribution of this feature would be greatly appreciated.

**Comment by sedmelluq** [comment]
Metadata is now supported for all OGG audio codecs.
