### ISSUE TITLE
Enable log.debug output?

### ISSUE THREAD

**Issue by downtoearthdev** [sedmelluq/lavaplayer#145]
I'm having an issue loading a track and I see all the log.debug() statements in the code, and would like to know how to be able to see them.

**Comment by napstr** [comment]
Lavaplayer uses the [slf4j](https://www.slf4j.org/manual.html). You need to use an implementation of that in your project.

**Comment by downtoearthdev** [comment]
> Lavaplayer uses the [slf4j](https://www.slf4j.org/manual.html). You need to use an implementation of that in your project.

Got it, I have the Simple implementation, however there are no errors. I'm trying to load a local file using the path to the file, but the AudioResultHandler fires noMatches() each time. The same files loaded over http:// work fine, just not locally. Lavaplayer does checks to see if the file exists and if it can be read from, and these pass fine., I'm not sure what is failing after that as I received no output aside the code in noMatches() firing.

**Comment by napstr** [comment]
Probably an issue with how your file paths look like that you are passing into lavaplayer. That issue would probably be best and fastest solved in the lavaplayer channel of the JDA Discord server: https://discord.gg/0hMr4ce0tIk3pSjp

**Comment by downtoearthdev** [comment]
I was using only AudioSourceManagers.registerRemoteSources() and should have also used AudioSourceManagers.registerLocalSource(), this resolved this issue! Thank you!
