### ISSUE TITLE
Scheduler is broken

### ISSUE THREAD

**Issue by FocusZTV** [sedmelluq/lavaplayer#147]
Hi,

I have an issue with my whole track scheduler. When i try to skip, it stops the song and doesnt play whatever is next in the queue, and doesnt add songs to the queue properly, and doesnt detect when a track has ended.

 It also doesnt let me change the volume of the player, pause it or stop it, as it throws a Null Pointer Exception. 

If this helps, I am using lava player with JDA and JDA-Utils.

Thanks

**Comment by MCOfficer** [comment]
that sounds eerily like a problem with your code - not lavaplayer. issues are supposed to be for bug reports, feature requests and the like. if you want, you can join the [JDA discord server](https://discord.gg/0hMr4ce0tIk3pSjp) which has a lavaplayer support channel.

**Comment by sedmelluq** [comment]
Ditto above, plus if there is an exception, it is useless to report without a full stack trace.
