### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by BroManDudeGuyPhD** [sedmelluq/lavaplayer#15]
Havent changed my code at all. Getting issues when loading playlists or certain videos. https://paste.ofcode.org/hN2957C8rKXwb3uAFE9AcM

Here is the song attempting to play in the error. https://www.youtube.com/watch?v=f9EFW1yaQzA
It IS from a playlist.

**Comment by BroManDudeGuyPhD** [comment]
Here is the song attempting to load in the error. It is from a playlist. https://www.youtube.com/watch?v=f9EFW1yaQzA

**Comment by Frederikam** [comment]
Looks like your version of lavaplayer is out of date. This exception was fixed in `1.1.41`

**Comment by BroManDudeGuyPhD** [comment]
Was a versioning issue! Thanks
