### ISSUE TITLE
Permissions issue when downloading libraries to /tmp if another user has already written to /tmp

### ISSUE THREAD

**Issue by alfonsojon** [sedmelluq/lavaplayer#153]
I was recommended to leave a bug report here. I use a program called JMusicPlayer, which uses this project as a library. I am currently running JMusicPlayer on multiple user accounts on my Ubuntu Server. The bots crash when they play a song, as the folder `/tmp/lava-jni-natives/1544694529585` already exists and belongs to another user.

I think a good workaround to this issue would be to use a user-specific `tmp` folder or append the username of the current user to the directory in `/tmp`.

Line Reference:
https://github.com/sedmelluq/lavaplayer/blob/b0c536098c4f92e6d03b00f19221021f8f50b19b/common/src/main/java/com/sedmelluq/discord/lavaplayer/natives/NativeLibLoader.java#L96

**Comment by alfonsojon** [comment]
#154

**Comment by sedmelluq** [comment]
No response, closing as the original solution does not seem viable.

**Comment by alfonsojon** [comment]
@sedmelluq if I delete the contents of /tmp it works fine. The issue is caused by more than one user on the same system trying to access the same folder in /tmp. Sorry for the lack of a response, haven't been on GitHub much lately and missed the email.

My solution is just a workaround.
