### ISSUE TITLE
Spotify Support?

### ISSUE THREAD

**Issue by EnderDev** [sedmelluq/lavaplayer#155]
It would be great if you could specify a spotify playlist `https://open.spotify.com/user/example/playlist/7FUhHHAYHhHjVsJdDrNxNs?si=GhUj2yhcSRG6-vOFpMFhD`, for example that.

**Comment by MCOfficer** [comment]
likely not going to happen due to Spotify's restrictions. Even if one could "crack" spotify's login- and play-system (i already spent days on it and failed, and judging by the absence of working spotify downloaders, i'm not the only one), it'd be strictly against their ToS.

**Comment by EnderDev** [comment]
alright thanks!

**Comment by KewaiiGamer** [comment]
the following bot https://github.com/emre1702/BonusBot uses Spotify Web API to play Spotify videos . Groovy bot also allows playing from Spotify so I really doubt that it's a breach of their ToS

Couldn't you use that API to implement native spotify support into Lavaplayer?

**Comment by MCOfficer** [comment]
> the following bot [emre1702/BonusBot](https://github.com/emre1702/BonusBot) uses Spotify Web API to play Spotify videos . Groovy bot also allows playing from Spotify so I really doubt that it's a breach of their ToS
> 
> Couldn't you use that API to implement native spotify support into Lavaplayer?

That's hardly native. The API only exposes track information. The bot you posted loads track information from spotify and then does a YouTube search to find their audio.

**Comment by duncte123** [comment]
> the following bot https://github.com/emre1702/BonusBot uses Spotify Web API to play Spotify videos . Groovy bot also allows playing from Spotify so I really doubt that it's a breach of their ToS
> 
> Couldn't you use that API to implement native spotify support into Lavaplayer?

The way those bots do it is by searching YouTube for the tracks and playing those instead

**Comment by proohit** [comment]
I have implemented a similar workflow on my Bot at [https://github.com/proohit/DirisSlave/](https://github.com/proohit/DirisSlave/). 

It uses the [search endpoint](https://developer.spotify.com/documentation/web-api/reference/search/search/) and transmits a **search string** inside the **q** query. You must also provide a **type** query, e.g. tracks. The server returns the requested type, e.g. tracks. Those have author and title properties, which I give to the [YoutubeAudioSourceManager](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/YoutubeAudioSourceManager.java) to search for matching videos.

I've done authentication via [client credentials flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#client-credentials-flow).

For your case you could [GET the playlist](https://developer.spotify.com/documentation/web-api/reference/playlists/get-playlist/) and parse the **tracks** to an AudioSourceManager, e.g. YoutubeAudioSourceManager
