### ISSUE TITLE
Error when the queue is finish.

### ISSUE THREAD

**Issue by Draagoo25** [sedmelluq/lavaplayer#156]
When my queue is finished, I got an error in console
Here it is the error:
> https://pastebin.com/uJghJ61N

Here it is the class where the error occurs:
> https://pastebin.com/yqsqwLBm

**Comment by Devoxin** [comment]
Call `player.getGuild().getAudioManager().closeAudioConnection();` from another thread, or update your JDA (IIRC Minn changed JDA's AudioManager to no longer throw on CloseAudioConnection).
