### ISSUE TITLE
Youtube Playlist Wrong loading

### ISSUE THREAD

**Issue by gamerjungexd** [sedmelluq/lavaplayer#165]
Hi,

If I am entering a Playlist in the loadTrack() and the input is a ytsearch: playlist.
Then I dont get back the right playlist. I got only one song or another Playlist.
Also If im only searching for Strings like "ytsearch: SDP" or "ytsearch: KDA" He wants to get me a full playlist.

Is that a bug with the playlists?

**Comment by MCOfficer** [comment]
If you pass a string that starts with `ytsearch`, lavaplayer loads a playlist containing all search results. The usual way to deal with this is to only queue the first track.

if you already have a playlist's URL, just pass it to `loadTrack` without the `ytsearch:` prefix

**Comment by gamerjungexd** [comment]
Mhhh but now I am filtering if its a playlist and if I now try it with for example this link:https://www.youtube.com/watch?v=oUiOylPbfV0&list=PLJ9wRRCY-gY1YMnDTThA6HW-5dFIc9z-V

There is noMatches().

**Comment by gamerjungexd** [comment]
Ah got It fixed. Unfortunally I casted the URI to lowercase xD
