### ISSUE TITLE
String format typo

### ISSUE THREAD

**Issue by CyberKiller** [sedmelluq/lavaplayer#167]
The second replacement field in this string is a "{]" instead of "{}":
https://github.com/sedmelluq/lavaplayer/blob/ff0815a62f1ebf7f40f8a6136364cb643a93d475/common/src/main/java/com/sedmelluq/lava/common/natives/NativeLibraryLoader.java#L196

**Comment by sedmelluq** [comment]
Fixed, will be in the next release.
