### ISSUE TITLE
SoundCloud Playlist won't play

### ISSUE THREAD

**Issue by Min0w** [sedmelluq/lavaplayer#178]
I can play individual songs on soundcloud, but cannot play soundcloud playlists (even if they are public)
I do not have any error, I have the message saying that the playlist is loaded, but there is absolutely no sound. I first thought this could be a loading time, but it isn't as a two songs playlist wouldn't play too.

**Comment by MCOfficer** [comment]
Did you resolve it?

**Comment by Min0w** [comment]
Yes, I forgot a line.
