### ISSUE TITLE
LOAD_FAILED EndReason Youtube

### ISSUE THREAD

**Issue by gamerjungexd** [sedmelluq/lavaplayer#181]
Hi, 

I didn't change anything in my code for the Lavaplayer and how he queued the songs. At the moment some songs are can be queued and other not. I search via ytsearch:  and this is the string
`"ytsearch: sdp"` 
Then he finds this song:
https://www.youtube.com/watch?v=PGEpUuloh44

Same for this:
`"ytsearch: slipknot"`
https://www.youtube.com/watch?v=VpATBBRajP8

But he cannot play it. I check this for some more of the videos from the channel. 
But if I search for example for KDA or so he find something and can queue it without a fail. 
`"ytsearch: KDA"`
https://www.youtube.com/watch?v=UOxkGD8qRB4

In this example I skipped 2 times. There i queued 2 times kda. then slipknot. He founds the right song, but at the load he failed and throw me this as endreason in a sysout.

```
Console: {
STOPPED
STOPPED
LOAD_FAILED
}

Discord Chat:{
The Current Queue:
[1]
K/DA - POP/STARS (ft Madison Beer, (G)I-DLE, Jaira Burns) | Official Music Video - League of Legends
[2]
Slipknot - Unsainted [OFFICIAL VIDEO]
}
```

Oh also to mention. before a few weeks the songs I tried to play here worked completly fine. So it is not the first time I queue for this songs.

I tested this also now on a other bot from a friend. He is using also the lavaplayer, but he can queue these songs. Some ideas why?

**Comment by napstr** [comment]
Please post logs.

**Comment by gamerjungexd** [comment]
I didn't get any log. I just find this fail, because I sysout the endReason of the songs in the TrackScheduler which extends from the AudioEventAdapter. Also I got no Fail message in the AudioLoadResultHandler. In my debug I also see the songs with the right uri and so on. the right track, but they instantlly end with the reason FAILED.

**Comment by napstr** [comment]
If your Lavalink server is not doing any logs, its probably not running, and there's your problem.

**Comment by gamerjungexd** [comment]
I can queue some other songs, like I already wrote. I just have a simple bot, where I used the lavaplayer in his simplest form. I never saw any logs or worked with the lavalink server. It just worked like described in the tutorial(readme)

**Comment by MCOfficer** [comment]
set your logging level to DEBUG and try to reproduce it, you should get a stacktrace
