### ISSUE TITLE
Some videos not playable 1.3.17

### ISSUE THREAD

**Issue by ToxicMushroom** [sedmelluq/lavaplayer#183]
When trying to play the following video "https://cdn.discordapp.com/attachments/368370633098133504/590967443170787330/cat_scream.mp4" WARNING EARRAPE.
I get this exception https://hasteb.in/ciwazoyu.yaml
I have the same problem with lots of other songs, other people also can't play this using lavaplayer.

**Comment by Shadorc** [comment]
This issue is still present in 1.3.20
Here is an updated stacktrace: https://pastebin.com/80e18NHd

**Comment by ToxicMushroom** [comment]
this has long been fixed
