### ISSUE TITLE
Certain (many) tracks are not playing, throwing exception

### ISSUE THREAD

**Issue by PhaseRush** [sedmelluq/lavaplayer#185]
youtube url: www.youtube.com/watch?v=k8zuqsqdCAQ 
error: https://hastebin.com/xegahuguzi.pl

this is one of many examples of songs that are giving

**Comment by Devoxin** [comment]
Update your lavaplayer version.

**Comment by PhaseRush** [comment]
> Update your lavaplayer version.

Fixed. Mine was on 1.3.7
I thought it was on 1.3.17

Need better glasses.
