### ISSUE TITLE
No Sound Problem

### ISSUE THREAD

**Issue by BurakDKX** [sedmelluq/lavaplayer#186]
Hi i wanted to make a jda music bot but i tried many tutorials etc. bot giving no sound and any exception giving. I am using 1.3.17 version and tried to JDA Native Sound lib but anything changed. How i can fix it this problem ?

**Comment by nateradev3** [comment]
I am having a similar issue. I noticed when I debug the code I can make it start working, but it's almost as if the thread reading the audio stream is ahead of the buffer.  If I debug line 336 in MatroskaStreamingFile for a bit.  Then allow the code to continue executing it begins working until the playlist runs out. I am trying to find the source of the issue. I am still unsure what other thread is running when the main audio loop is running.  I may need to do a thread dump and go from there. It's likely that it's some sort of race condition, but I am unsure why it does not seem to be affecting most people.

**Comment by nateradev3** [comment]
To give an update.  It turned out my issue was not with the audio player, but with the jda library.  
https://github.com/DV8FromTheWorld/JDA/issues/717
