### ISSUE TITLE
[Question] YouTube livestreams

### ISSUE THREAD

**Issue by BannerBomb** [sedmelluq/lavaplayer#190]
Is this supposed to support youtube live streams? Cause when I try to play one it errors with
```
18:25:50.076 [JDA [0 / 1] AudioConnection Guild: [guild_id_here] Sending Thread] ERROR: track [youtube_track_id_here] stuck with thresholdMs 10000
```

**Comment by sedmelluq** [comment]
Can you include some sample stream that it happens for? Also, make a thread dump if possible (after you start playing it but before the stuck event fires).

**Comment by BannerBomb** [comment]
The stuck event fires as soon as it is executed to start playing. I chose a random stream cause I was testing to see if it supported live streams from youtube, but the url for the livestream I tested with was https://www.youtube.com/watch?v=oZzQC8NVTeM.

**Comment by sedmelluq** [comment]
The specified stream works and various livestream issues have been fixed since, so it's likely the specific cause was fixed. Feel free to report an issue if this is encountered again on the latest version.
