### ISSUE TITLE
Can't play some video on youtube in 1.3.18

### ISSUE THREAD

**Issue by RedHeadEmile** [sedmelluq/lavaplayer#198]
Hello, I tried to play some video, some work and some does't work, example:
https://www.youtube.com/watch?v=MUyLUE9mWw0 work
https://www.youtube.com/watch?v=uA2VHxLQbkA work

https://www.youtube.com/watch?v=pbMwTqkKSps does't work
play https://www.youtube.com/watch?v=3zrbCDdGjwc does't work

No exception, no error, I don't know why, I'm running on 1.3.18
Sorry, I don't have any Exception to report

**Comment by MCOfficer** [comment]
are you sure your logging configuration didn't swallow the error?

**Comment by RedHeadEmile** [comment]
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[main] INFO JDA - Login Successful!
[JDA MainWS-WriteThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO JDA - Finished Loading!
START CLIENT MANAGER ON PORT 4514`

**Comment by MCOfficer** [comment]
oh, well. you might want to *get* a logger first. consult the first link, or just add logback-classic as dependancy.

**Comment by RedHeadEmile** [comment]
It is a bit raw but I have an exception
https://pastebin.com/XpNQNpSy

**Comment by duncte123** [comment]
Update to 1.3.19

**Comment by RedHeadEmile** [comment]
Thank you 👍
