### ISSUE TITLE
Cannot compile on linux

### ISSUE THREAD

**Issue by fcr--** [sedmelluq/lavaplayer#2]
[..]
CMake Error at udpqueue/CMakeLists.txt:27 (add_library):
  Cannot find source file:

    linux/timing.c
[..]

As far as I can see, the directory udpqueue-natives/udpqueue/linux (with timing.c & mutex.c) is missing

**Comment by fcr--** [comment]
Anyway, I just attached a simple version that I made of this wrapper (in case anyone else needs it)...

[linux.zip](https://github.com/sedmelluq/lavaplayer/files/632269/linux.zip)

**Comment by sedmelluq** [comment]
Thanks for the files. The udpqueue module is actually not part of lavaplayer itself, but of an experimental component for handling sending the packets to discord from a native thread to survive GC pauses without hiccups. But indeed it is confusing that some parts of the project don't compile, so I will add them (will continue with this component at some point anyway, it will need to work on Linux then also).
