### ISSUE TITLE
Loading information for a YouTube track failed.

### ISSUE THREAD

**Issue by SaudBina** [sedmelluq/lavaplayer#202]
> [15:44:53] [INFO] [Startup]: Loaded config from /root/config.txt
> [15:44:54] [INFO] [JDA]: Login Successful!
> [15:44:55] [INFO] [WebSocketClient]: Connected to WebSocket
> [15:44:57] [INFO] [JDA]: Finished Loading!
> [15:45:00] [INFO] [AudioManager]: Audio System successfully setup!
> [15:45:04] [ERROR] [DefaultAudioPlayerManager]: Error in loading item https://youtu.be/orGywIVoKp8
> com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
>         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:217)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromUrlWithVideoId(YoutubeAudioSourceManager.java:307)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromShortDomain(YoutubeAudioSourceManager.java:287)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadNonSearch(YoutubeAudioSourceManager.java:314)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:189)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:128)
>         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
>         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
>         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
>         at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException: null
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:213)
>         ... 14 common frames omitted
> 

But the problem only works if I run the jar files on my owns VPS, but if I run it in my local network its work without issues

**Comment by SaudBina** [comment]
the update is 1.3.19 
and i try 1.3.17 but don't with local network and vps ,
but 1.3.19 only works in local network .

**Comment by SaudBina** [comment]
actually i use IntelliJ , if u run the application its work but if i build it its dont work it

**Comment by Frederikam** [comment]
Update to `1.3.19`. See #199
