### ISSUE TITLE
Some tracks just don't work properly.

### ISSUE THREAD

**Issue by Deivu** [sedmelluq/lavaplayer#204]
Relevant logs to the problem: https://pastebin.com/A6VVq2ZF

I was trying to play this playlist when that problem occured, and not only on single song, almost all the songs was skipped due to that error log.
Playlist Link: `https://www.youtube.com/playlist?list=PLckeMyCaCCIN_JU1V4oADW50DlGOREoLj`

**Comment by Devoxin** [comment]
This should be fixed in 1.3.20.

**Comment by Deivu** [comment]
Can confirm. Thanks for the release.
