### ISSUE TITLE
NoClassDefFoundError for DaemonThreadFactory

### ISSUE THREAD

**Issue by proohit** [sedmelluq/lavaplayer#206]
I know this has been issued sometimes, but I still can't get to get it to work. I followed the usage instructions in the readme.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sedmelluq/lava/common/tools/DaemonThreadFactory
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<init>(DefaultAudioPlayerManager.java:106)
	at audioplayer.AudioPlayer.<init>(AudioPlayer.java:26)
	at Commands.<init>(Commands.java:26)
	at MyEventListener.<init>(MyEventListener.java:9)
	at Main.main(Main.java:12)
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.lava.common.tools.DaemonThreadFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO JDA - Finished Loading!
```

I used Gradle to add the dependency, but I must admit that I have never used it before. I tried to look for the class myself, which I did in gradle: 
![image](https://user-images.githubusercontent.com/46965017/63886346-91f02a00-c9da-11e9-8fb2-45b9564d019a.png)

Now that the class is actually there, why am I getting this Exception? What's interesting to note is that if I go into the **DefaultAudioPlayerManager** and **URLClassLoader** classes, both of them show no error at usage of **DaemonThreadFactory**.

This is how my build.gradle looks like:
```
repositories {
    jcenter()
}

dependencies {
    compile 'com.sedmelluq:lavaplayer:1.3.20'
    compile 'com.sedmelluq:lavaplayer-common:1.0.6'
}
```
**Note**: I have tried with and without including lavaplayer-common, but I think since it is transitive anyway I cannot simply overwrite it

**Comment by MCOfficer** [comment]
this has been brought up [a couple times already](https://github.com/sedmelluq/lavaplayer/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+daemonthreadfactory+). the class should be in lava-common, afaik lavaplayer-common is not being used anymore.

**Comment by proohit** [comment]
yes, that's why i first tried it without including lavaplayer-common. As I showed in the screenshot above, the class seems to be there and my IDE shows no error when opening the throwing classes.

**Comment by proohit** [comment]
Ok I got it to work. The problem was that the libraries have been **downloaded** via Gradle, but not added to the **classpath**!
This was done via IntelliJ, so here is my solution: When included the lavaplayer dependency, go into File>Project Structure>Modules>Your Module>Dependencies (on the right tab) then click on the + and select all libraries relevant for lavaplayer. This way all libraries will be added to the classpath and will be found.

**Comment by MCOfficer** [comment]
> 
> 
> Ok I got it to work. The problem was that the libraries have been **downloaded** via Gradle, but not added to the **classpath**!
> This was done via IntelliJ, so here is my solution: When included the lavaplayer dependency, go into File>Project Structure>Modules>Your Module>Dependencies (on the right tab) then click on the + and select all libraries relevant for lavaplayer. This way all libraries will be added to the classpath and will be found.


before having to resort to stuff like this, just don't use the intellij build system to begin with (or only use it to execute gradle tasks).
