### ISSUE TITLE
libconnector.so:  Operation not permitted in /TMP

### ISSUE THREAD

**Issue by Sasiko** [sedmelluq/lavaplayer#212]
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1568318308672/libconnector.so: /tmp/lava-jni-natives/1568318308672/libconnector.so: failed to map segment from shared object: Operation not permitted

centos 7 on /tmp/
its mounted with tmpfs /tmp tmpfs rw,noexec,nosuid 0 0

and thats to prevent malicious peopl from executing scripts. 

Is there anyway to avoid storing files from /tmp folder and let us choose a storage path?

**Comment by sedmelluq** [comment]
You can set `lava.native.connector.extractPath` system property to specify the exact path where it should be extracted to.

**Comment by sedmelluq** [comment]
Closing as answer was provided long ago.
