### ISSUE TITLE
Lavaplayer > 1.3.10 is missing x86/32-bit natives

### ISSUE THREAD

**Issue by Bleuzen** [sedmelluq/lavaplayer#215]
Hi, I noticed that since version 1.3.11, there are no native libraries for 32-bit systems anymore. So lavaplayer now does not work on x86 systems.
Did you want to remove x86 support or is it a bug?

**Comment by sedmelluq** [comment]
This is intentional. Actual x86 hardware is practically non-existent nowadays, so pretty much every occasion of using x86 JDK is due to either accidentally installing x86 JDK on a x64 OS, or accidentally installing x86 OS on x64 hardware.
