### ISSUE TITLE
Building a fat jar

### ISSUE THREAD

**Issue by stefan-reich** [sedmelluq/lavaplayer#216]
Hi,

how do I make a fat jar of LavaPlayer including the native libraries on Linux? I got it compiled in Gradle, but am not sure how to package the whole thing.

**Comment by napstr** [comment]
Have you tried the [shadow plugin](https://github.com/johnrengelman/shadow) or the [spring boot plugin](https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html)?

**Comment by stefan-reich** [comment]
I'm not really familiar with Gradle, sorry to say... for now I just merged all the jars manually, minus the native libs. Might work too, I'm testing.

**Comment by stefan-reich** [comment]
I think this worked, thanks
