### ISSUE TITLE
Unable to play most YouTube livestreams

### ISSUE THREAD

**Issue by robinfriedli** [sedmelluq/lavaplayer#219]
Lavaplayer seems to be unable to play most of the YouTube livestreams I've tried. No exception is thrown but when attempting to play a URL that points to a currently active livestream lavaplayer does not play anything but fires a TrackStuckEvent immediately. Reproducible with https://www.youtube.com/watch?v=dG_uLbD3-qY , should be online for a few more days.

**Comment by aikaterna** [comment]
Upgrade to Lavaplayer 1.3.47 and livestream playback is resolved... for now.

**Comment by sedmelluq** [comment]
^
