### ISSUE TITLE
setVolume not working

### ISSUE THREAD

**Issue by Seblofs** [sedmelluq/lavaplayer#225]
When we try to set the volume this error cames, but it doenst even make sense:
Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.NoSuchMethodError: 

```
> org.slf4j.helpers.MessageFormatter.format(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/String;
>         at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:535)
>         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.log(ExceptionTools.java:107)
>         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103)
>         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:835)
> Exception in thread "Timer-1" java.lang.NullPointerException
>         at commands.cmdMusic$4.run(cmdMusic.java:286)
>         at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
>         at java.base/java.util.TimerThread.run(Timer.java:506)
```
here is the setvol cmd:
`case "vol":
                if(args.length == 1) {
                    sendSuccsesMsg(event,"Die aktuelle Lautstärke ist **" + getPlayer(guild).getVolume() + "%**");
                } else {

                    if (args[1].length() > 2) {
                        event.getTextChannel().sendMessage(
                                new EmbedBuilder().setColor(Color.ORANGE)
                                        .setDescription("<:confirm:509070945948925962> | **AUA**, das tut mir (und dir?) weh :( Aber ich höhre auf dich, egal wie viel!")
                                        .build()
                        ).queue();
                    }
                    try {
                        int vol = Integer.parseInt(args[1]);
                        getPlayer(guild).setVolume(vol);
                        sendSuccsesMsg(event, "Neue Lautstärke: **" + vol + "%**");
                    } catch (Exception e) {
                        sendErrorMsg(event, "Entweder musst du eine **Zahl**, keinen **Buchstabe**, angeben oder deine **angebene Zahl**, war **zu laut** für mich und meine Ohren wären tot.");
                    }
                }
                break;`

**Comment by napstr** [comment]
Use a proper build tool like Maven or Gradle to build your jar.

**Comment by Seblofs** [comment]
I use maven, here my pom.xml
`        <dependency>
            <groupId>com.sedmelluq</groupId>
            <artifactId>lavaplayer</artifactId>
            <version>1.3.22</version>
        </dependency>`

**Comment by sedmelluq** [comment]
The `NullPointerException` is clearly in your own code, thus your issue is not related to Lavaplayer.
