### ISSUE TITLE
Is it possible to use your library as a regular media player?

### ISSUE THREAD

**Issue by Grouen** [sedmelluq/lavaplayer#23]
Hello, I want to learn how to use your library for normal playback (as a regular media player). If so, how?

**Comment by sedmelluq** [comment]
Yes, it's possible. You have to set the output format to PCM:
```java
```

**Comment by sedmelluq** [comment]
Yes, it's possible. You have to set the output format to PCM, for example:
```java
manager.getConfiguration().setOutputFormat(new AudioDataFormat(2, 44100, 960, AudioDataFormat.Codec.PCM_S16_BE));
```

And a class which makes it easy to get an AudioInputStream from the player is also included in the library. Example:
```java
AudioInputStream stream = AudioPlayerInputStream.createStream(player, manager.getConfiguration().getOutputFormat(), 10000L, false);
```

Which can then be use with Java's audio classes. A full example is here:
https://github.com/sedmelluq/lavaplayer/blob/master/testbot/src/main/java/com/sedmelluq/discord/lavaplayer/demo/LocalPlayerDemo.java

**Comment by Grouen** [comment]
Thank you very much for your detailed response.
