### ISSUE TITLE
Version needs to be incremented

### ISSUE THREAD

**Issue by BoneyIsSpooky** [sedmelluq/lavaplayer#235]
Hello,

I can't use the direct link fix introduced in df9e1f2 because the library version was not incremented. The most recent version on JCenter is not the one with the fix.

Thanks

**Comment by BoneyIsSpooky** [comment]
Is there no word on this? Increasing the version seems like an extremely easy fix that would enable me to use the latest version of the library, please address this.

**Comment by MCOfficer** [comment]
> 
> 
> Is there no word on this? Increasing the version seems like an extremely easy fix that would enable me to use the latest version of the library, please address this.

i would assume that this is an easy fix and will happen eventually, but at the moment sedmelluq simply doesn't have time for it.

**Comment by s-frei** [comment]
> 
> 
> Is there no word on this? Increasing the version seems like an extremely easy fix that would enable me to use the latest version of the library, please address this.

In the meantime you could build it yourself and publish it to maven local. Waiting for an increased & deployed version too.

**Comment by s-frei** [comment]
Btw, https://github.com/sedmelluq/lavaplayer/commit/df9e1f2517d5d157ce3f99c93f124043e90ec4a5 isn't working anymore. Two PRs are open for that.

**Comment by Shadorc** [comment]
1.3.23 is available since yesterday
https://bintray.com/sedmelluq/com.sedmelluq/lavaplayer/1.3.23
