### ISSUE TITLE
"AudioTrack#makeClone()" Does not copy User Data.

### ISSUE THREAD

**Issue by WesternPine** [sedmelluq/lavaplayer#236]
When using the `AudioTrack#makeClone()` method, it does not copy AudioTrack's User Data that could have been set using `AudioTrack#setUserData(Object object)`.

Reading the docs, I do see that `AudioTrack#makeClone()` states it clones the track with the exception of the track's "execution state", but I'm pretty sure the User Data isn't related to the execution state, and **SHOULD** be copied.

**Comment by sedmelluq** [comment]
Done in `1.3.25`.

**Comment by WesternPine** [comment]
Thank you bb!
