### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by KortyBoi** [sedmelluq/lavaplayer#249]
Could you try looking into support for YouTube Music?

I see this is used for jagrosh's Music bot. It would be great if you could add support for the following link: https://music.youtube.com/watch?v=x[&list=x]

**Comment by Devoxin** [comment]
`music.youtube.com` already [looks to be handled by LP.](https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubeLinkRouter.java#L17)

**Comment by KortyBoi** [comment]
Oh, I didn't see that, thanks.
