### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by DiamondIceNS** [sedmelluq/lavaplayer#25]
I'm attempting to use lavaplayer with JDA for a Discord bot and I'm running into the following exception:

`java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1489710936108/libconnector.so: /lib64/libm.so.6: version 'GLIBC_2.15' not found (required by /tmp/lava-jni-natives/1489710936108/libconnector.so) `

I think it's telling me that the libconnector.so on the server was compiled against the wrong GLIBC version, but I'm walking through the code in the repo and it's not clear to me where it's actually trying to pull libconnector.so from. It seems to expect the server to have its own preexisting copy, I suppose? I guess this is more of a question of how the library actually works than a problem with it.

The server in question is a virtual one that I rent, so I don't have full control over it. I pointed the libconnector.so temp directory to a place I could access and listed its members with readelf and I'm finding lots of version markers for 2.2.5, which tells me something is outdated. If it really is a server problem, let me know so I can bring it up with my host.

**Comment by Frederikam** [comment]
Your distro's version of glibc is out of date. You might need to update your system. You're likely running centos.

**Comment by DiamondIceNS** [comment]
Does the glibc version need to be exactly 2.15 or can it be higher?

**Comment by Frederikam** [comment]
Any somewhat recent version of glibc should work.

**Comment by DiamondIceNS** [comment]
Sounds like this problem is probably out of my control then. Thank you for the swift information.
