### ISSUE TITLE
Incompatibility with shadowJar

### ISSUE THREAD

**Issue by zaap38** [sedmelluq/lavaplayer#253]
I'm using IntelliJ IDEA.

When I launch my bot from the IDE, the audio is working, but when I export it with shadow and execute the .jar, it's not.
All the other functionnality that are not audio are still working.

Note that the bot is joining voice in both cases.

**Comment by MCOfficer** [comment]
Do you get any logs on debug level?

**Comment by zaap38** [comment]
After few tests, I have this:

**Running with IDE:**
The used .mp3 isn't into the generated .jar but into the build/.../...mp3
A System.out show me that the file is passing via the "play" function.

**Running with JAR (via powershell)**
The used .mp3 is the one into the archive (build/libs/....jar/......./...mp3).
The System.out do not appear (so not passing by "play" System.out).

I precise that in both cases I pass by the function calling the "play" function and both path are correct.
There's no error log into the console.

**Comment by zaap38** [comment]
Error i get when I try to run a youtube song with powershell (the error loops) :
`[JDA AudioConnection Guild: 364422776632901633 Sending Thread] ERROR DefaultSendSystem - Uncaught exception in audio send thread
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at com.sedmelluq.discord.lavaplayer.demo.jda.AudioPlayerSendHandler.provide20MsAudio(AudioPlayerSendHandler.java:41)
        at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacketRaw(AudioConnection.java:677)
        at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:664)
        at net.dv8tion.jda.api.audio.factory.DefaultSendSystem.lambda$start$0(DefaultSendSystem.java:69)
        at java.lang.Thread.run(Unknown Source)`

This error isn't happening when using IntelliJ to launch.
Local .mp3 files are not providing this error at all (but they are still not working, even when they are not into the .jar).

**Comment by sedmelluq** [comment]
The cause is that even when specifying source&target as JDK 8 when compiling on JDK 11, it will compile calls to `ByteBuffer` methods in a way that won't actually work on JDK 8.

Change `buffer.flip();` in your `AudioPlayerSendHandler` to `((Buffer) buffer).flip()`.
