### ISSUE TITLE
Soundcloud likes with unavailable tracks error on load

### ISSUE THREAD

**Issue by nikammerlaan** [sedmelluq/lavaplayer#260]
https://soundcloud.com/arti-the-pro/likes This fails to load because one of the last songs in there is blocked in the United States, so SC doesn't send any transcodings.

**Comment by MrUnknownDE** [comment]
Simply because error logs are included: D
[https://github.com/jagrosh/MusicBot/issues/335](https://github.com/jagrosh/MusicBot/issues/335)
