### ISSUE TITLE
AudioLoadResultHandler trackLoaded never get called

### ISSUE THREAD

**Issue by Foakx** [sedmelluq/lavaplayer#263]
I have my own Discord Bot included Lavaplayer and my Bot worked without problems. Today i tryed to add that i can choose between 5 titles but now the Function trackLoaded never get called anymore (i didnt modifyed anything there, only in playlistLoaded)
trackLoaded doesnt output anything in System.out.println
Please help!
Full Code in File
[cmdMusic.zip](https://github.com/sedmelluq/lavaplayer/files/4007089/cmdMusic.zip)

**Comment by sedmelluq** [comment]
You had not added anything to the implementation `noMatches` or `loadFailed`, one of which was likely called. In the unlikely scenario that you can confirm that none of those get called either, make a thread dump shortly after the load attempt is made and create a new issue with that included.
