### ISSUE TITLE
Use it as a custom Java Swing Player App ?

### ISSUE THREAD

**Issue by JibayMcs** [sedmelluq/lavaplayer#266]
Hi,

I know this library is mainly used to make discord bots, but it's possible to use it as a java audio player ?

I need to have some audio datas, but I don't know how to get it, and play it on computer speaker by example.

Anyone made a java player with this library ? (I found nothing on net) (it's possible btw ?)
The features to player Youtube or Soundcloud audio is what I need.

If anyone coul'd help me !

Best regards.

**Comment by sedmelluq** [comment]
See `LocalPlayerDemo` class in testbot module.

**Comment by JibayMcs** [comment]
> See `LocalPlayerDemo` class in testbot module.

![](https://media1.tenor.com/images/109cd0904c6a8f185bb19ffc402f8b6d/tenor.gif?itemid=3893691)

Thanks a lot ! 💜
