### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by elgoupil** [sedmelluq/lavaplayer#27]
Hi i cant compile, i dont rly know how to do it and when i test with gradlew build the error is:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\renardn\Desktop\lavaplayer-master\lavaplayer-master\natives
\build.gradle' line: 119

* What went wrong:
Execution failed for task ':natives:connector-32-setup'.
> Cannot run program "cmake" (in directory "C:\Users\renardn\Desktop\lavaplayer-
master\lavaplayer-master\natives\build\tmp\vsloc"): CreateProcess error=2, File not found

**Comment by FinKsu** [comment]
I have same issue

**Comment by ducc** [comment]
@Virus57000 @FinKsu did you solve this issue? Just ran into it.

**Comment by Sadiinso** [comment]
I also have the same issue :/

**Comment by Sadiinso** [comment]
I have installed Cmake + All Visual Studio C/C++ modules, then change the native/gradle.build line 126 to target correctly the "devenv.exe" file, but it's still fail to compile the opus lib. Even if I try to compile it manually with the VS command prompt.

**Comment by ducc** [comment]
![screenshot](https://i-hate.dabbot.org/638c21.png)

**Comment by Sadiinso** [comment]
Now, it tell me that it can't read the "mpg123.lib" file. Same result if I compile myself the required C libs.

**Comment by jakecrowley** [comment]
Has the same problem, fixed by running command prompt as administrator then running gradlew build

**Comment by sedmelluq** [comment]
As it is not normally intended that you compile your own native libraries, moved native libraries to a separate dependency, so that the main module does not trigger native builds.
