### ISSUE TITLE
Support for TabletopAdudio.com tracks

### ISSUE THREAD

**Issue by MockLogic** [sedmelluq/lavaplayer#271]
This is a feature request. My apolgies if this is the wrong spot for it.

Any chance of getting LavaPlayer to play TabletopAudio.com tracks?  The composed tracks specifically, not the sound pads.

I'm currently using Redbot (which uses Lavaplayer) for background audio in Discord chat when running RPGs, and while I can download the files to local and then play them, it would be nice to be able to just play them directly, especially as new songs are added to the site.

**Comment by sedmelluq** [comment]
Please provide a sample url to a specific track.

**Comment by MockLogic** [comment]
https://tabletopaudio.com/download.php?downld_file=196_Crossing_the_Styx.mp3

**Comment by MCOfficer** [comment]
That can already be played with HTTP source manager. A Feature request only makes sense when you have a page from which links should be extracted (for example https://soundcloud.com/thefatrat/thefatrat-monody-feat-laura-brehm-1/)

**Comment by sedmelluq** [comment]
Closing as sample link already works with HTTP source.
