### ISSUE TITLE
Something broke when playing the track.

### ISSUE THREAD

**Issue by RaknaX** [sedmelluq/lavaplayer#278]
Sometimes I get this error when I try to open a video from YouTube.
`Something broke when playing the track.`

How can I solve this?
Note: I use Lavalink.

**Comment by MCOfficer** [comment]
This is impossible to tell without the full log. Set your logger to debug level and take note of the stacktrace - "Something broke" is just the generic error message.

**Comment by sedmelluq** [comment]
No response to request for additional data in over half a year, closing.
