### ISSUE TITLE
Feature: A more detailed event sytem (AudioEventListener)

### ISSUE THREAD

**Issue by LowLevelSubmarine** [sedmelluq/lavaplayer#286]
Wouldn't it be possible to seperate onAudioEvent in for example: onStop, onPlay, onStateChange(boolean paused) and so on.
And a option to mute the events for stopTrack() (and the other methods that create events) would be awesome. Like: stopTrack(boolean notify)

**Comment by LowLevelSubmarine** [comment]
[https://imgur.com/a/A1g22B9](temporary solution) xD

**Comment by Devoxin** [comment]
`onStop` -> `onTrackEnd` (there is `endReason` that details why the track was stopped).
`onPlay` -> `onTrackStart`
`onStateChanged` -> I could be wrong but this might already be a thing? If not, considering player pause state is only managed by the user, you can implement this on your end.

> And a option to mute the events 

Seems redundant.

**Comment by LowLevelSubmarine** [comment]
Closing the issue, because i didn't knew about the Adapter
