### ISSUE TITLE
Problem of playing track from youtube : speed (2x)

### ISSUE THREAD

**Issue by NayKeys** [sedmelluq/lavaplayer#288]
I dont know why, everything is working well (except adding a playlist) but each video (from youtube) that i'm trying to play is readed in 2x speed ! Also in every guild (and new guilds too) !

**Comment by Devoxin** [comment]
As mentioned in [this issue](https://github.com/DV8FromTheWorld/JDA/issues/1248#issuecomment-608561892), this is a problem with your code.

**Comment by sedmelluq** [comment]
Closing as it is not a lavaplayer issue.
