### ISSUE TITLE
Bot join on vc but nothing happens

### ISSUE THREAD

**Issue by neinkop** [sedmelluq/lavaplayer#289]
Hey
I have a problem with using Lavaplayer when I want to play a song, the bot gets into the VC but doesn't play anything. I copied the code from the example.
Does anybody know why or had the same problem before?

**Comment by Klemms** [comment]
I had to upgrade my server to Java 13 for it to work on debian, it worked on Java 8 on Windows though

**Comment by MCOfficer** [comment]
You need to provide a bit more info.

- what OS are you running it on?
- What java version?
- how are you running it?
- which lavaplayer version?
- is there anything in the debug logs?

**Comment by sedmelluq** [comment]
Closing as no additional details were provided.
