### ISSUE TITLE
Youtube Video Starting at Certain Time

### ISSUE THREAD

**Issue by totietje** [sedmelluq/lavaplayer#38]
It would be nice to have an option in the YoutubeAudioSourceManager to be able to player a youtube video from a certain time. Maybe something like `loadTrackWithVideoId(String videoId, int seconds, boolean mustExist);`?

**Comment by Frederikam** [comment]
Why? You can set the position of an AudioTrack before playing it.

**Comment by totietje** [comment]
Ah ok, I missed that feature. I'll close this issue. Thanks.
