### ISSUE TITLE
ytsearch is returning no results found for every query

### ISSUE THREAD

**Issue by ducc** [sedmelluq/lavaplayer#45]
This is temporarily fixed by restarting however it quickly breaks again (could be do to with volume of requests).
Version: 1.2.42

**Comment by ducc** [comment]
Disabling cookie persistence for youtube searching fixes this. Tested method (using reflection): 
```java
class DabYoutubeAudioSourceManager extends YoutubeAudioSourceManager {
  DabYoutubeAudioSourceManager() {
    super(true);

    try {
      // getting the httpInterfaceManager variable
      Field field = this.getClass().getSuperclass().getDeclaredField("httpInterfaceManager");
      field.setAccessible(true);

      // removing the final modifier
      Field modifiersField = Field.class.getDeclaredField("modifiers");
      modifiersField.setAccessible(true);
      modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);

      // creating a new HttpClientBuilder with cookie management disabled
      HttpClientBuilder httpClientBuilder = HttpClientTools.createSharedCookiesHttpBuilder()
              .disableCookieManagement();

      // creating a new HttpInterfaceManager with our HttpClientBuilder
      HttpInterfaceManager httpInterfaceManager = new ThreadLocalHttpInterfaceManager(httpClientBuilder,
              HttpClientTools.DEFAULT_REQUEST_CONFIG);

      // setting the new value of the field
      field.set(this, httpInterfaceManager);
    } catch (NoSuchFieldException | IllegalAccessException e) {
      e.printStackTrace();
    }
  }
}
```
Untested but avoiding reflection & probably doing it the right way: @Shredder121
```java
youtubeAudioSourceManager.configureRequests(config -> 
    RequestConfig.copy(config)
            .setCookieSpec(CookieSpecs.IGNORE_COOKIES)
            .build()
);
```

**Comment by Shredder121** [comment]
Just to cover my bits when people say "there is no such (static) method in `YoutubeAudioSourceManager `"
```java
YoutubeAudioSourceManager youtube = new YoutubeAudioSourceManager(true);
youtube.configureRequests(config ->
        RequestConfig.copy(config)
                .setCookieSpec(CookieSpecs.IGNORE_COOKIES)
                .build()
);
```

**Comment by ducc** [comment]
^shredder's method has been tested and apparently doesn't work

**Comment by Shredder121** [comment]
Crosspost from Discord, since this seems to be the issue.
It's not a cookie problem, but it seems the DOM layout changed.

So, finally had the issue of not being able to search locally.
Peppered some breakpoints, and it seems the `durationElement` is null.
So, hmmm, there is another `video-time` related class in the DOM.
There's `video-time-overlay` that seems to have the right content we need for the time computation.
![dom screenshot](https://media.discordapp.net/attachments/263484072389640193/341483147734679552/unknown.png?width=1443&height=550)

**Comment by sedmelluq** [comment]
Closed as the relevant PR was merged.
