### ISSUE TITLE
When requesting a song, you load infinitely

### ISSUE THREAD

**Issue by benzarr410** [sedmelluq/lavaplayer#46]
I've tried everything, restarting, trying links AND search terms, different songs, youtube AND soundcloud, but nothing seems to work,

**Comment by SimonCraenen** [comment]
I seem to be having the same issue.

**Comment by MedicOP** [comment]
Same issue. None of the methods in ResultHandler are ever called

**Comment by sedmelluq** [comment]
As I am not able to reproduce, debug in the following way:

- Set a breakpoint on `DefaultAudioPlayerManager#createItemLoader` lines `boolean[] reported = new boolean[1];` and `return null;`.
- Run your application and let it call `loadItem`.
- Wait to see if the first breakpoint is hit (max 10 sec). If not, report here and don't continue.
- Continue execution and wait to see if the second breakpoint is hit (max 10 sec). If yes, report here with lavaplayer logs.
- If the second breakpoint was not hit, make a thread snapshot and include it here.

**Comment by sedmelluq** [comment]
No response in over a month, closing until further details are provided.
