### ISSUE TITLE
Unknwon Operating System : FreeBSD

### ISSUE THREAD

**Issue by mdiepart** [sedmelluq/lavaplayer#461]
Hi,
I was trying to use lavaplayer through Jagrosh's MusicBot.
After trying to manually update lavaplayer to it's latest version to fix the youtube 404 error i got it working fine on my desktop (Win 10). However when I tried running it on my server (FreeNas 11.3 that is FreeBSD 11.3) I got it working but once I tried to change the volume the bot stopped working.
I checked the logs and it seems that lavaplayer is complainign about my operating system being unknown.

Error stacktrace: https://pastebin.com/kc8LWR7G
Lavaplayer Version: 1.3.46
Operating system: FreeBSD 11.3-RELEASE-p7
Java version: Tested with openJDK8 and openJDK11 (got the same error).

Thank you for your work and your help !

**Comment by aikaterna** [comment]
FreeBSD is not supported.

**Comment by Emzi0767** [comment]
You have to compile the native components of Lavaplayer for FreeBSD, then modify the native loader to recognize FreeBSD and load appropriate binaries.

**Comment by sedmelluq** [comment]
I currently have no plans to build natives for FreeBSD. But if someone does, they can point LP to load it by setting the `lava.native.connector.system` system property, no code changes needed.
