### ISSUE TITLE
[Question] Maybe an Issue: "ytsearch: " not working 

### ISSUE THREAD

**Issue by dragonriderworld** [sedmelluq/lavaplayer#462]
Hello, I've setup a Dicord Bot wit Music, etc.
Right now the Music Player only works with links. If i type in Some Search Words (sorry for my bad English) The bot joins my Channel, but nothing happens.

And yes i add a "ytsearch: " to the Search Words, before I give them to the AudioPlayerManager.loadItem().

Did I miss something, or is it a momentarily bug on your side?

**Comment by Devoxin** [comment]
Override the `loadFailed` and `noMatches` methods and add some logging. If there's an error with your query, Lavaplayer will call `loadFailed`, if your query yields no tracks, Lavaplayer will call `noMatches`.

**Comment by dragonriderworld** [comment]
Ok....I've teste around a little bit and found out, that it always outputs into the playlistLoaded(). Even if i search for the exact title of a video. Don't know if thats how it should be, but I don't think so.

**Comment by Devoxin** [comment]
This is intentional.
Search results are classed as a playlist because they return multiple tracks. You can differentiate between a playlist and a search result by checking whether `AudioPlaylist#isSearchResult` returns true.
