### ISSUE TITLE
Feature Request: Video Support

### ISSUE THREAD

**Issue by cloudybyte** [sedmelluq/lavaplayer#469]
Discord recently added a feature that enables users in guilds to stream video, not just in private calls.
I think it would be nice to have the video stream in addition to the audio to do sth like music video viewing similar to watch2gether in discord... It that possibile?

**Comment by MCOfficer** [comment]
might be possible, but either way that strays very far from LP's scope. Would probably require a rewrite while they're at it, so while i can't speak for sed, i don't see this happening.

**Comment by cloudybyte** [comment]
I investigated further and found out that video streaming is currently not supported for bot accounts...
-Closed-
(I will eventually reopen this issue when the feature becomes available)
