### ISSUE TITLE
Feature Request: Equalizer

### ISSUE THREAD

**Issue by PercyJW-2** [sedmelluq/lavaplayer#470]
Is it possible to implement something like an equalizer, similar to the volume controls that already exist?  
I would like to implement something like a Bass-Boost for my Music-Bot and as far as I know it needs to be implemented into the Library to be able to do something like this.

**Comment by nikammerlaan** [comment]
Lavaplayer already has an equalizer filter implemented. https://github.com/sedmelluq/lavaplayer/blob/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/filter/equalizer/EqualizerFactory.java

**Comment by PercyJW-2** [comment]
Is there an example how to use it?
