### ISSUE TITLE
Some audio can't be played

### ISSUE THREAD

**Issue by Diniboy1123** [sedmelluq/lavaplayer#471]
Good day,

I am using a lavalink embedded lavaplayer on x64 platform and trying to play AAC files from a HTTP source which is my local server. I made sure that the endpoint always returns the correct content-type header: audio/aac, and in most cases the audio plays though there are a few media files that fail constantly. Lavaplayer plays a sharp scratching sound then stops after usually a few seconds and skips to the next song. Though the audio file seems to be playing fine in any local media player I have and upon bumping an ffmpeg corruption check, the audio seems to be perfect and not lacking headers.

The stacktrace I am getting:

```
Warning: Big change (MPEG version, layer, rate). Frankenstein stream?
[src/libmpg123/layer3.c:496] error: Blocktype == 0 and window-switching == 1 not allowed.
[src/libmpg123/layer3.c:2016] error: bad frame - unable to get valid sideinfo

Warning: Big change (MPEG version, layer, rate). Frankenstein stream?
Note: Illegal Audio-MPEG-Header 0x448163e4 at offset 146848.
Note: Trying to resync...
Note: Skipped 1024 bytes in input.
[src/libmpg123/parse.c:1273] error: Giving up resync after 1024 bytes - your stream is not nice... (maybe increasing resync limit could help).
2020-04-26 10:19:46.478 ERROR 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of <redacted>

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
```

And here is a mediainfo of a broken file:

```
General
Complete name                            : resolve.aac
Format                                   : ADTS
Format/Info                              : Audio Data Transport Stream
File size                                : 6.80 MiB
Overall bit rate mode                    : Variable

Audio
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 4
Codec ID                                 : 2
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 6.80 MiB (100%)
```

Feel free to DM me from the JDA guild under Mary Johanna#0420 to ask for a test file.

**Comment by sedmelluq** [comment]
Prioritized detecting as AAC in case the audio/aac mime type is set, to avoid it accidentally getting detected as MP3 in that case. More reliable distinction between AAC and MP3 might be necessary in the long term, but as that may require decoding the actual data, will postpone for now.
