### ISSUE TITLE
Max songs in playlist loaded

### ISSUE THREAD

**Issue by ReikoTigon** [sedmelluq/lavaplayer#472]
Hello, 
atm there seems to be max song cap at 600 for YouTube playlists.
Is there a way to disable that?

Thanks for your help :)

**Comment by Devoxin** [comment]
YoutubeAudioSourceManager.setPlaylistPageCount(int pages)

**Comment by dragonriderworld** [comment]
Thanks. this will help me a lot...
hmmm...could you tell me how to use it? xD

How do I initialize the YoutubeAudioSourceManager/Where do I get the informations from - the player?

But thanks a lot already^^

**Comment by Devoxin** [comment]
```java
YoutubeAudioSourceManager ytasm = new ...();
ytasm.setPlaylistPageCount(100);

audioPlayerManager.registerSourceManager(ytasm);
```

**Comment by sedmelluq** [comment]
Closing as it is solved.
