### ISSUE TITLE
[Question] ytsearch

### ISSUE THREAD

**Issue by benma0005** [sedmelluq/lavaplayer#476]
When I search something with "ytsearch: " than it addds 19 songs to my queue.
```java 
String input = Arrays.stream(args).skip(1).map(s -> " " + s).collect(Collectors.joining()).substring(1);

                if (!(input.startsWith("http://") || input.startsWith("https://"))) {
                    input = "ytsearch: " + input;
                } 
```
is my maybe code wrong or what is my mistake

**Comment by MCOfficer** [comment]
when using `ytsearch`, it doesn't give you a track but rather a playlist of search results. If you want to use the first track of the results, add a check for `AudioPlaylist#isSearchResult` in your `playlistLoaded` method.
