### ISSUE TITLE
Audio Stuttering

### ISSUE THREAD

**Issue by CorruptComputer** [sedmelluq/lavaplayer#48]
I have been trying to figure out why my bot's audio stutters and I think it may be an issue with lavaplayer. At first I thought the issue was with Discord4J, as I have been told this is an issue if I use its built in audio player, but I am using lavaplayer for my audio. My bot is based on this example provided: https://github.com/decyg/d4jexamplebot 

Is there an issue with that that causes the audio to stutter, or should I just live with it and assume its normal?

**Comment by CorruptComputer** [comment]
Ah, I realize it might help to have my exact code: https://github.com/GrumpyCode/PolizziaHut/tree/master/src/main/java/com/grumpycode/polizziahut

**Comment by KyuBlade** [comment]
What version of D4J do you use?

**Comment by CorruptComputer** [comment]
2.8.4 and here is the new link to my repo: https://github.com/CorruptComputer/PolizziaHut/tree/master/src/main/java/me/nickolasgupton/polizziahut

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sedmelluq** [comment]
If you are still having issues, you can try to count how many `null` frames the `AudioPlayer` gives after the first few seconds of playing a new track. If there are `null` frames, then it may be a lavaplayer issue, otherwise it definitely is not.

**Comment by sedmelluq** [comment]
No response in over a month, closing until further details are provided.
