### ISSUE TITLE
Allow http.proxyHost and other system properties to be used

### ISSUE THREAD

**Issue by Adi3000** [sedmelluq/lavaplayer#482]
For a complete usage of SystemProperties, using `useSystemProperties()` on HttpClientBuilder could be useful.

https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html

May be done on `ExtendedHttpClientBuilder.build` or  `AbstractHttpInterfaceManager` constructor. Don't really know which one is better

**Comment by sedmelluq** [comment]
Quite simple to enable by:
```
manager.setHttpBuilderConfigurator(HttpClientBuilder::useSystemProperties);
```
or
```
sourceManager.configureBuilder(HttpClientBuilder::useSystemProperties);
```
I don't see much point enabling this by default at the moment.
