### ISSUE TITLE
LavaPlayer says the playlist does not exist, but it actually does

### ISSUE THREAD

**Issue by cloudrac3r** [sedmelluq/lavaplayer#491]
It seems to be an issue with this playlist only. Opening the link in a browser works. <https://www.youtube.com/playlist?list=OLAK5uy_nVKRV1KVLAe2EalfHjEsVKBLpXxj3Mlw4>

Other playlists work fine.

It might be due to this playlist's ID starting with OL. NewPipe says that it has no author and that it is auto-generated by YouTube.

I'm using Lavalink, but I'm about 90% sure that the code that's causing this is from LavaPlayer.

**Comment by RinLovesYou** [comment]
plays fine on lavaplayer for me

**Comment by sedmelluq** [comment]
Does not reproduce with the latest version.
