### ISSUE TITLE
Loading information for a YouTube track failed.

### ISSUE THREAD

**Issue by Aw3s0m3PL** [sedmelluq/lavaplayer#497]
Hello.
I am getting this message every time i am trying to play any song.
There are no errors in console. Just this message on discord chat.
 I am using loadAndPlay(channel, url) code.

**Comment by Aw3s0m3PL** [comment]
`if (isUrl(mess[1])) {
									mg.loadAndPlay(e.getChannel(), mess[1]);
									return;
								}
								else {
									String msg = e.getMessage().getContentRaw();
									msg = msg.replace("!dj", "");
									String ytSearched = searchYoutube(msg);
									if (ytSearched == null) {
										ch.sendMessage(":x: Brak wyników wyszukiwania w serwisie YouTube.").queue();
										return;
									}
									else {
										mg.loadAndPlay(e.getChannel(), ytSearched);
										
									}
									return;
								}`

**Comment by MitchHS** [comment]
I had this issue yesterday aswell. Was only happening in a compiled jar, but I reset my router and flushed dns which seemed to fix it on my pi 3.

**Comment by sedmelluq** [comment]
If you encounter this again, report together with full exception details.
