### ISSUE TITLE
Cannot play local files on Mac OS

### ISSUE THREAD

**Issue by Blogshot** [sedmelluq/lavaplayer#5]
When playing locally stored files i get the following error:

Stacktrace:
http://pastebin.com/DqLsr3pC

I am compiling and running on Mac OS X.

build.gradle:
```
repositories {
[...]
    jcenter()
}
dependencies {
[...]
    compile 'com.sedmelluq:lavaplayer:1.1.37'
}
```

The files are valid and can be played with other players.

**Comment by sedmelluq** [comment]
OS X support is planned. Will keep it open until I finish it.

**Comment by sedmelluq** [comment]
OS X support is there now.
