### ISSUE TITLE
Occasional Error While Playing Track

### ISSUE THREAD

**Issue by mandm635** [sedmelluq/lavaplayer#50]
Some tracks (from yt) are skipped in the middle or at the beginning. This is what I get in my logs: 

[https://pastebin.com/2vgB0icz](https://pastebin.com/2vgB0icz)

I'm using D4J and almost the example integration with some minor changes.

**Comment by napstr** [comment]
```Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out```
Looks like bad net to me.

**Comment by sedmelluq** [comment]
The issue might be mitigated by newer versions which also retry on socket timeouts. But probably mostly caused by network issues. An exception is live streams where it may be caused by Lavaplayer being too impatient when waiting for next segment which is not yet available.
