### ISSUE TITLE
ytsearch: is only playing Playlists

### ISSUE THREAD

**Issue by Nightloewe** [sedmelluq/lavaplayer#502]
We used "ytsearch: counting stars" and got a playlist full of videos playing Counting Stars.

**Comment by Frederikam** [comment]
That's a feature. You could play the first track or give the user the option to choose which one of the tracks to play.

**Comment by Nightloewe** [comment]
Maybe you should notice this in the README, so that user know that for search results, playlistLoaded also get called.
