### ISSUE TITLE
Youtube stream

### ISSUE THREAD

**Issue by ZzmaxzZ81** [sedmelluq/lavaplayer#506]
If I play a video that was a stream like: 
![image](https://user-images.githubusercontent.com/68784849/88464089-33685000-ceb8-11ea-8b4d-f3c06616c72c.png)
https://www.youtube.com/watch?v=cSGmtcXOy8o
(Live PS5 for example)

Then the bot doesn't play the video.
No error in the console
Look the duration:
![image](https://user-images.githubusercontent.com/68784849/88463834-15015500-ceb6-11ea-927b-95b6b62d536d.png)
getDuration() returns a too large long
![image](https://user-images.githubusercontent.com/68784849/88463910-9bb63200-ceb6-11ea-8d4c-e832eb1e4131.png)
is that normal?

Using last version 1.3.50
(I'm bad at English, so I put a lot of pictures ^^)

**Comment by kimcore** [comment]
`9223372...` is `Long.MAX_VALUE`, which means the track is live stream. You should add check for `track.info.isStream` which tells you if the track is a live stream.

**Comment by sedmelluq** [comment]
Works fine on latest version, with correct length detected.
