### ISSUE TITLE
ytsearch: doesn't work

### ISSUE THREAD

**Issue by NetRiceCake** [sedmelluq/lavaplayer#507]
I am using lavaplayer with jda.
It worked well when I used it before, but it doesn't work now.
All functions except ytearch operate normally.

Is there a solution?

**Comment by MCOfficer** [comment]
Please post more information such as the stacktrace, your lavaplayer version etc.

**Comment by NetRiceCake** [comment]
`event.getChannel().sendMessage("Searching...").queue(response -> {
            if (myId == 0) myId = response.getMember().getIdLong();
            audioPlayerManager.loadItem("ytsearch:" + argument, new FunctionalResultHandler(null, list -> {
                response.delete().queue();
                event.getChannel().sendMessage("There are search results").queue();
            }, () -> { response.delete().queue(); event.getChannel().sendMessage("No search results.").queue(); }, e -> { response.delete().queue(); event.getChannel().sendMessage("Error: " + e.getMessage()).queue(); }));`

This is part of my code.
It says "No search results." whichever word I enter.
And I'm using the most recent version of the lavaplayer.

**Comment by BomBardyGamer** [comment]
can you post your logs in a bin service of your choice? (I recommend https://bin.bardy.me)

**Comment by NetRiceCake** [comment]
Fixed myself
