### ISSUE TITLE
Lavaplayer stops after 3-6secs with this error

### ISSUE THREAD

**Issue by yadibolt** [sedmelluq/lavaplayer#511]
Hello,

So from today I have an issue with lavaplayer.

Lavaplayer stops after 3-6sec of playing and exit with error below.
![unknown](https://user-images.githubusercontent.com/56600402/89456733-984b6200-d764-11ea-9724-09029b3cf3f0.png)

I'm trying to play a stream from youtube.
Tried updating to the latest version and trying older ones too, with the same error.

**Comment by sedmelluq** [comment]
Fixed in `1.3.56`.
