### ISSUE TITLE
Sometimes when I load an item, "java.lang.RuntimeException: No player info block." is thrown

### ISSUE THREAD

**Issue by gaborszita** [sedmelluq/lavaplayer#515]
Sometimes when I load an item to play, lavaplayer throws the Exception "java.lang.RuntimeException: No player info block.". This doesn't happen always - only sometimes. It even only happens sometimes when I load the same track. I'm having no internet connection issues. Is youtube rate limiting me? If yes, then what can I do? I have my own Youtube API key from Google, which I use to make youtube searches, if that matters. But I don't use this API key anywhere in lavaplayer, I use it for my own classes.

This is the full error I get:
![image](https://user-images.githubusercontent.com/30361931/90958436-d8188600-e494-11ea-9d0b-0c4e483a4d57.png)

**Comment by Litarvan** [comment]
Same issue here

**Comment by duncte123** [comment]
I'm getting this same exception with a lot of consistency, https://pastebin.com/k6M1phWW

**Comment by brys0** [comment]
Been getting the same issue.

**Comment by playerdecuple** [comment]
I am still having the same problem.
(I'm sorry that I'm using Google Translate because I'm not good at English.)

**Comment by duncte123** [comment]
Update to version 1.3.53

**Comment by playerdecuple** [comment]
Thanks :)
