### ISSUE TITLE
Playing an mp3 File

### ISSUE THREAD

**Issue by tornaduuu** [sedmelluq/lavaplayer#522]
I only want the bot to play an mp3 file in an voice channel. I dont want to create an TrackScheduler or anything, I only want the bot to join the channel an play an short mp3 if i write an command (ive programmed the command part already)

**Comment by MCOfficer** [comment]
How is that an issue with lavaplayer? If you want support you can join #lavaplayer on the [JDA Discord](https://discord.gg/0hMr4ce0tIk3pSjp) - but don't expect to be spoonfed.

**Comment by redbrain** [comment]
If you're looking for short mp3 playback on command, lavaplayer might be overkill. https://github.com/cm/airhorn implements something similar in pure discord.js/opus.

**Comment by sedmelluq** [comment]
Closing as this isn't an issue with the library.
