### ISSUE TITLE
Bandcamp urls are not working

### ISSUE THREAD

**Issue by aikaterna** [sedmelluq/lavaplayer#526]
The source manager for Bandcamp is not able to find the base url for the artist in the page nor the track listings in an album page. I had a previous fix working at https://github.com/sedmelluq/lavaplayer/pull/518 but the page format changed again within the last few days and that fix is now invalid. 

The track listing on an album page does not seem easily-extractable now, although the bandUrl string for an artist can be found on either track pages or album pages in the href under <span itemprop="byArtist">.

The friendly error returned for trying to play a track or album page is "Band information not found on the Bandcamp page.", which starts with finding the bandUrl and building from there. If anyone needs detailed tracebacks I can provide them, but there's not much insight there and it's easily reproducable with any Bandcamp track.

**Comment by JDCourtney1969** [comment]
Hi.  I'm just a spectator here - a heavy user of Bandcamp who has used a couple of programs and web sites to convert many Bandcamp tracks to WAV files.   As of about a week ago, I am no longer able to produce large WAV files.   Someone told me it has something to do with "youtube-dl"...?  I am guessing it's a result of some changes made by people at Bandcamp....?     Is anyone else aware of this and has anyone tried to address this?   Either here, or in a different place (pull request?) on this site?   I am very new to this site and am having trouble navigating.  I'm just desperate to get this issue resolved.   Can anyone please help, or tell me where to go to find help?    Thank you!

**Comment by duncte123** [comment]
You could just buy the tracks.....

**Comment by aikaterna** [comment]
@JDCourtney1969 You should look at the issues page on the youtube-dl github page then and see if they have fixed it yet.
https://github.com/ytdl-org/youtube-dl
This isn't the right github repository for youtube-dl questions.

**Comment by aikaterna** [comment]
This has been resolved in the U-Lavaplayer fork @ 1.3.58+
