### ISSUE TITLE
How do you queue tracks?

### ISSUE THREAD

**Issue by JordanPlayz158** [sedmelluq/lavaplayer#529]
I have attempted to use "PlayerManager.getInstance().getGuildMusicManager(guild).scheduler.queue(tracks.get(i));" but I can't due to it requiring an AudioTrack and I've tried a variety of ways to convert a String to an AudioTrack but no luck, I was hoping someone could help me as there are no JavaDocs, detailed documentation/wiki, etc.

**Comment by MCOfficer** [comment]
check the README: https://github.com/sedmelluq/lavaplayer#loading-audio-tracks

**Comment by JordanPlayz158** [comment]
Oh yeah I saw and tried that and have read the whole readme and was just confused about what the identifier is but after rereading that I now understand, thank you for your help!

**Comment by JordanPlayz158** [comment]
Wait, I'm back on desktop and just realized that, that is the whole issue, I can't load the audiotrack because it is looking for an AudioTrack but doesn't seem to give a way to convert the trackUrl to an audiotrack (other than when you try to load and play but I just want to queue the audiotracks not play them instantly or they will overlap each other.

**Comment by MCOfficer** [comment]
the part where you start playback is *your* code. Call loadItem, and you get an AudioTrack. Just don't queue it.

**Comment by JordanPlayz158** [comment]
Oh I see, I was able to figure it out, thank you!
