### ISSUE TITLE
Cannot resolve symbol

### ISSUE THREAD

**Issue by rphlmnbt** [sedmelluq/lavaplayer#530]
![image](https://user-images.githubusercontent.com/70652892/94560721-9c43be00-0295-11eb-91f7-9082e3428323.png)
I get an issue whenever I try to use the sample code given in the description.
It says "Cannout resolve symbol 'registerRemoteSources' even though I have included lavaplayer on my build.gradle file.
I have also tried invalidating cache and restarting. Thanks.

**Comment by MCOfficer** [comment]
Please provide your LP version.

**Comment by rphlmnbt** [comment]
> Please provide your LP version.

![image](https://user-images.githubusercontent.com/70652892/94563917-f21a6500-0299-11eb-9158-eebeaf044166.png)
I'm using 1.3.50.
I'll try using a different IDE and see how it works out.

**Comment by rphlmnbt** [comment]
Closing this issue. Its working and I literally don't know what fixed it. I even tried it on both Windows and Linux.
