### ISSUE TITLE
.getInfo().title always  returning null

### ISSUE THREAD

**Issue by Relliks44** [sedmelluq/lavaplayer#531]
Everytime I use ".getInfo().title" it returns null I tried multiple songs (wich had youtube titels ofc). ".getInfo().author" and ".getInfo().uri" works fine. I also tried using differend versions of Lavaplayer but this always happens and a VPN.

**Comment by Relliks44** [comment]
An old version of my bot that I developed 5 month ago wich worked totaly fine at the time is also not working now.

**Comment by MCOfficer** [comment]
Can you provide the LP versions you tested with?

**Comment by Relliks44** [comment]
I tried Lavaplayer version 1.3.47, 1.3.49, and LATEST (1.3.50 I guess)

**Comment by Shadorc** [comment]
This is fixed (with other things) in this fork: https://github.com/Devoxin/lavaplayer/tree/1.3.51
`implementation 'com.github.Devoxin:lavaplayer:1.3.53'` on `jitpack`

**Comment by Relliks44** [comment]
IntelliJ is not findig a version 1.3.51 
![image](https://user-images.githubusercontent.com/67743549/94996517-75430000-05a5-11eb-8c67-16076efc9b4f.png)

**Comment by Shadorc** [comment]
Yes because there is no .51
This is another repo, a fork

**Comment by Relliks44** [comment]
Oh I think I got it. Its working now. Thank you verry much.
