### ISSUE TITLE
Broken Maven dependencies/NoClassDefFoundError

### ISSUE THREAD

**Issue by Nagispace** [sedmelluq/lavaplayer#532]
Hello I have a NoClassDefFoundError and when looking at [this](https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md) page I tried the following maven command
```
mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:tree -Dverbose=true
```
and then saw the following warning
```
[WARNING] The POM for com.sedmelluq:lavaplayer:jar:1.3.50 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```
I have the following stack trace when trying to call `new DefaultAudioPlayerManager()`

```Exception in thread "main" java.lang.NoClassDefFoundError: com/sedmelluq/lava/common/tools/DaemonThreadFactory
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.<init>(DefaultAudioPlayerManager.java:106)
	at command.music.NiqueAudio.init(NiqueAudio.java:17)
	at Main.main(Main.java:42)
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.lava.common.tools.DaemonThreadFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more
```

The attached file is the full result of the maven dependency tree output.
[maven_dependencies_out.txt](https://github.com/sedmelluq/lavaplayer/files/5365766/maven_dependencies_out.txt)

Edit: The same file but with the debug output
[maven_dependencies_out_with_debug.txt](https://github.com/sedmelluq/lavaplayer/files/5365798/maven_dependencies_out_with_debug.txt)

**Comment by sedmelluq** [comment]
The invalid part of the POM it is quoting "<!d" is not present actually present. It is likely that JCenter served a different result due to some temporary issues on their side. If this happens again, delete the cache and have it redownload the POM. If that fails, verify that the contents of the cached file are equal to the one in https://jcenter.bintray.com/com/sedmelluq/lavaplayer/ and report if it is.
