### ISSUE TITLE
Cannot queue the ended track

### ISSUE THREAD

**Issue by JustAPieOP** [sedmelluq/lavaplayer#535]
When i tried to queue the ended track, it threw me an error saying: "Cannot play the same instance of track. Use track.makeClone() instead"

**Comment by proohit** [comment]
How about trying the hint? Instead of queuing `track` queue `track.makeClone()`

**Comment by JustAPieOP** [comment]
i tried but nothing happened

**Comment by proohit** [comment]
How do you invoke it, can you provide an example?

**Comment by JustAPieOP** [comment]
well, i use track.makeClone() directly each time a track ends

**Comment by proohit** [comment]
I can only guess how your method(s) like but this works in my not:
```
@Override
    public void onTrackEnd(AudioPlayer player, AudioTrack track, AudioTrackEndReason endReason) {
        if (endReason.mayStartNext) {
            if (isRepeat) queue(track.makeClone());
            nextTrack();
        }
    }
```

**Comment by JustAPieOP** [comment]
oh, so the `track.makeClone()` only make a "clone" of the track but not add that track to the queue directly

**Comment by proohit** [comment]
Yes, it creates an independent instance of that track. Play state etc are not copied this way.

**Comment by JustAPieOP** [comment]
Oh, thank you. I'm closing this issue
