### ISSUE TITLE
ytsearch option friendly error

### ISSUE THREAD

**Issue by tomkeuper** [sedmelluq/lavaplayer#536]
So i followed an online tutorial on how to use lavaplayer and it all works fine, but when i try to use the ytsearch option It doesnt work consistenly. Sometimes it adds the search to the queue but other times it says it didnt find anything or that the load failed. I have been asking around and couldnt find any info about this, thats why im here.

When the load failed i get this errormessage 
https://pastebin.com/tJfn1ftD

Maybe this also has some usefull info:
![image](https://user-images.githubusercontent.com/29728836/96390930-21483600-11b7-11eb-8c31-4dee13b7bae0.png)

**Comment by MCOfficer** [comment]
See #517
