### ISSUE TITLE
Sometimes 'Unexpected response from YouTube'

### ISSUE THREAD

**Issue by BrainBaze** [sedmelluq/lavaplayer#539]
Full StackTrace: [https://controlc.com/fcc30d7e](https://controlc.com/fcc30d7e)

This happens sometimes when i try to !play youtube-link
But the same command (with the same yt-link)  works after a while... sometimes...
And sometimes the Bot joins the VC, but doesnt play anything :/

However, the link from the StackTrace is: https://www.youtube.com/watch?v=XjOAA18z9uw
Version: bec3995

If you need more info, tell me!

**Comment by Maexm** [comment]
I'm having the same issue here. YouTube playback either fail with "Unexpected response from YouTube" OR their end with reason "load_failed". I haven't changed my code and it always used to work.

I also noticed that lavaplayer cannot find anything on YouTube when searching for keywords (youtube:keyword). I wonder, do you experience this as well @BrainBaze ?

Links from SoundCloud seem to work fine.

**Comment by BrainBaze** [comment]
ty!
Is there a new Version for Maven or do I have to download the git repo?

**Comment by Shadorc** [comment]
Use Devoxin's fork, this repo is not maintened currently: https://github.com/Devoxin/lavaplayer
`implementation 'com.github.Devoxin:lavaplayer:1.3.59'` on `jitpack`

**Comment by menmaa** [comment]
You can use jitpack to download it directly from my github. [Check this example on gradle](https://github.com/menmaa/MenmuDiscordBot/commit/92d0676b1041d68242cf4093927a428a743f2ce3).

> Use Devoxin's fork, this repo is currently not maintened: https://github.com/Devoxin/lavaplayer
> `implementation 'com.github.Devoxin:lavaplayer:1.3.59'` on `jitpack`

Or this, whatever suits you better. I personally like my own solution better to this specific issue more.

**Comment by Portagoras** [comment]
> Use Devoxin's fork, this repo is currently not maintened: https://github.com/Devoxin/lavaplayer
> `implementation 'com.github.Devoxin:lavaplayer:1.3.59'` on `jitpack`

This fixed the issue for me!

**Comment by BrainBaze** [comment]
okay, i now use
`<groupId>com.github.menmaa</groupId>`
`<artifactId>lavaplayer</artifactId>`
`<version>a4b8b48ed5</version>`

My error mentioned above seems to be solved now!
Otherwise I will make a new Issue.

Thank you all for your incredible fast help!

**Comment by menmaa** [comment]
Added some workaround for an issue raised causing "Something went wrong loading the track.".
You can use new commit hash `737770c2a7` or you can use `master-SNAPSHOT` to get latest branch changes.
