### ISSUE TITLE
How to add ytsearch: to tracks

### ISSUE THREAD

**Issue by talentedasian** [sedmelluq/lavaplayer#543]
Whenever i play youtube by doing `ytsearch:` i only get one audio to play. When i try to play multiple youtube audios, it just doesnt go the queue. After the first track gets played, the second one just doesn't play. I have the minimal code that's in the demo btw

**Comment by MCOfficer** [comment]
https://github.com/sedmelluq/lavaplayer/blob/f1850fd725ecb25b0f98a520ae874863b405b9af/demo-jda/src/main/java/com/sedmelluq/discord/lavaplayer/demo/jda/Main.java#L80-L91

`ytsearch` loads a playlist of search results, so `playlistLoaded` is called. The example takes the easy route of queueing only the first track of that playlist (L85). If you want something different, you need to change this code.
Note that you can use `AudioPlaylist#isSearchResult` to tell regular playlists from search results.

If you need further support, please join the [JDA Discord](https://discord.gg/0hMr4ce0tIk3pSjp) and ask in #lavaplayer.

**Comment by talentedasian** [comment]
It's all good now I thought that the queue was automatically adding my tracks from your code above and it wasn't. I had to explicitly call `queue.add(track)`
