### ISSUE TITLE
Inconsistent track type determination on YouTube track

### ISSUE THREAD

**Issue by aikaterna** [sedmelluq/lavaplayer#544]
The video in question for this report is: https://www.youtube.com/watch?v=FLM2U9bAlgU which was a livestream at one point. 

Previous to Lavaplayer 1.3.53, playing this direct url would return the FriendlyException of "YouTube WebM streams are not currently supported." but using a ytsearch as described below would work. Now, at 1.3.53, the direct url will play but the video returns `106751991167:07:12:56` for the length (the livestream length long of `9223372036854775807`).

Playing the track in this manner with a direct url returns a Track with this information:
```
{
    "author": "Aggressive Records",
    "id": "FLM2U9bAlgU",
    "length": 9223372036854775807,
    "position": 0,
    "source": "youtube",
    "stream": false,
    "title": "ROOLER @ QAPITAL QONNECT 2020",
    "uri": "https://www.youtube.com/watch?v=FLM2U9bAlgU"
}
```

However, if a ytsearch: method is used for the song title "ROOLER @ QAPITAL QONNECT 2020" and the first result is enqueued, a different Track object is provided, with a sane length for the video:

```
{
    "author": "Aggressive Records",
    "id": "FLM2U9bAlgU",
    "length": 1865000,
    "position": 0,
    "source": "youtube",
    "stream": false,
    "title": "ROOLER @ QAPITAL QONNECT 2020",
    "uri": "https://www.youtube.com/watch?v=FLM2U9bAlgU"
}
```

**Comment by sedmelluq** [comment]
Fixed in `1.3.54`.
