### ISSUE TITLE
Cant Play YouTube Videos

### ISSUE THREAD

**Issue by scolastico** [sedmelluq/lavaplayer#549]
Hi, if i try to play a youtube video it doesnt works anymore. It worked a few weeks and scince a days it show's following error:
https://haste.scolasti.co/upoyuvaqaf.pl

My Source Code:
https://github.com/scolastico/disc0rd.exe/blob/hotfix-music-player/src/main/java/com/scolastico/discord_exe/etc/musicplayer/MusicPlayer.java

I allready tryd to update the player but nothing changed on the error.

**Comment by Portagoras** [comment]
Are you on the newest version? Cause that fixed it for me, I think.

**Comment by scolastico** [comment]
Yes im on 1.3.55
```
        <dependency>
            <groupId>com.sedmelluq</groupId>
            <artifactId>lavaplayer</artifactId>
            <version>1.3.55</version>
        </dependency>
```

**Comment by scolastico** [comment]
Oh i found the problem: IntelliJ didn't updated it properly. I needed to delete the cache and reinstall the maven dependencies...
