### ISSUE TITLE
YouTube playback seems to be a bit laggy

### ISSUE THREAD

**Issue by scolastico** [sedmelluq/lavaplayer#551]
If i play a song from youtube every n seconds the playback seems to lag for a second or so. I tryd to give the bot more cpu and ram bot nothing changes.

**Comment by sedmelluq** [comment]
Check https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md#45aba0a6

When giving more RAM, make sure you actually tell the JDK to use more (with -Xmx option).
