### ISSUE TITLE
can't play music on aarch64

### ISSUE THREAD

**Issue by Ludicrous245** [sedmelluq/lavaplayer#554]

**Comment by MCOfficer** [comment]
At first glance it sounds like #16 .

Regardless, if you want your issue to be taken seriously, please supply more information:

- LP version
- Stacktrace
- Does it happen with every piece of music, or just in specific cases?

**Comment by sedmelluq** [comment]
See See https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md#8d9389a5
