### ISSUE TITLE
Searching doesn't give livestreams

### ISSUE THREAD

**Issue by deebah** [sedmelluq/lavaplayer#564]
So basically, if I do "ytsearch: lofi 24/7", it doesn't give me what you would expect. When I look it up on youtube, it gives me: https://www.youtube.com/watch?v=5qap5aO4i9A, which is a live stream of course. when I do it in lavaplayer, it seems to skip all of the live streams and go right to one that isn't live. is there any way I can fix this?

**Comment by MCOfficer** [comment]
#107 #533
