### ISSUE TITLE
Add OpenBSD and FreeBSD to DefaultOperatingSystemTypes.java 

### ISSUE THREAD

**Issue by noobiangodd** [sedmelluq/lavaplayer#565]
Hello,

This is a feature request

Lavaplayer won't work correctly on OpenBSD and I assume also FreeBSD due to Unknown operating system type error.

The error looks like it originates from the code in this file (DefaultOperatingSystemTypes.java ).

I was able to successfully stream Opus through JMusicBot on OpenBSD which uses Lavaplayer, however couldn't convert m4a.

I believe if you handle OpenBSD and FreeBSD in the same way you do Linux and Solaris, the libraries will work as OpenBSD uses .so files pretty similar to Linux.

The osFullName for OpenBSD was 'OpenBSD'

Would it be possible to get OpenBSD (& maybe also FreeBSD) added to Lavaplayer?

Thank you

**Comment by sedmelluq** [comment]
This would require the native libraries to be compiled on them and included with LP. I have no interest in attempting that myself. If someone else actually gets them built, then I wouldn't mind adding the path autodetection for those (so for example would look in `natives/openbsd-x86-64` without having to specify `lava.native.connector.system=openbsd-x86-64`), but until then there is no point doing that.

**Comment by noobiangodd** [comment]
Hi,

Thanks for response

I will attempt to compile these, is the correct part that I need to compile lavaplayer/natives/?

Thanks

**Comment by Jake1702** [comment]
@noobiangodd Wondering if you ever happened to get the binaries compiled? I'd be interested in getting support for FreeBSD as well.

**Comment by noobiangodd** [comment]
> @noobiangodd Wondering if you ever happened to get the binaries compiled? I'd be interested in getting support for FreeBSD as well.

no I was in over my head, I don't understand Java and was trying to use the built in scripts to do it by tricking it to run on BSD. I feel like for someone who knows what they are doing more then I it would be a fairly trivial process.
