### ISSUE TITLE
Could not play: Received unxpected reponse from YouTube.

### ISSUE THREAD

**Issue by specownik** [sedmelluq/lavaplayer#566]
I use LavaPlayer version 1.3.63

If I perform these operations, the console displays the error:
Could not play: Received unxpected reponse from YouTube

CODE:
```
PlayerManager manager = PlayerManager.getInstance();
manager.loadAndPlay(event.getTextChannel(), "https://www.youtube.com/watch?v=FTLKdAU4XJM");
event.getMessage().addReaction("\uD83D\uDC4C").queue();
manager.getGuildMusicManager(event.getGuild()).player.setVolume(100);
```

**Comment by MCOfficer** [comment]
might be a case of #248. Can you post the full stacktrace?

**Comment by specownik** [comment]
Sure! Gives stacktrace on the hastebin to keep the thread from cluttering up.
https://hastebin.com/otinezuciw.properties

**Comment by sedmelluq** [comment]
As this ends with `Read timed out`, I've added a FAQ entry about timeouts:
https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md#63a9aae9

**Comment by sedmelluq** [comment]
No response in a month about whether changing timeouts helped, closing.
