### ISSUE TITLE
Bot loading track from youtube search but not playing any audio.

### ISSUE THREAD

**Issue by talentedasian** [sedmelluq/lavaplayer#568]
As the title says it. Nothin unusual in the logs except for it firing a cleanup because the bot won't play from the start. public 

```
            public void queue(AudioTrack track){
        // Calling startTrack with the noInterrupt set to true will start the track only if nothing is currently playing. If
        // something is playing, it returns false and does nothing. In that case the player was already playing so this
        // track goes to the queue instead.
        if (!player.startTrack(track, true) && !(queue.size() == 10)) {
            queue.offer(track);
        }
    }
```

That's my code for playing tracks.

**Comment by sedmelluq** [comment]
Cleanup means it is actually encoding and buffering audio, but your code is not consuming it.

**Comment by sedmelluq** [comment]
No response in a month, closing.

**Comment by ReikoTigon** [comment]
I actually have the same problem.

Atm i don't even have a queue. That means if I get a playlist I directly start the first track track from the playlist.
If it's a solo song I start it directly.

The command I am using is: `audioPlayer.startTrack(track, true)` and `startTrack(playlist.tracks[0], true)`

I call them directly from the Events (`playlistLoaded(playlist: AudioPlaylist)` and `trackLoaded(track: AudioTrack)`)
The `onTrackStart()` gets called too, as does the `onTrackEnd()` after a few seconds with the `AudioTrackEndReason "CLEANUP"`
