### ISSUE TITLE
Disable logger

### ISSUE THREAD

**Issue by Martijnpold** [sedmelluq/lavaplayer#57]
Any way to disable the logger? It's spamming the entire console.

**Comment by NachtRaben** [comment]
You can configure your own logger by configuring the slf4j implementation you use for logging.
Here is a basic one to filter all console messages from lavaplayer to "INFO".

https://gist.github.com/NachtRaben/aba6027b471211789d9618cc04840881

**Comment by sedmelluq** [comment]
No response to given solution, closing.
