### ISSUE TITLE
[Feature Request] Allow user to manually pass request headers to Lavaplayer?

### ISSUE THREAD

**Issue by redbrain** [sedmelluq/lavaplayer#574]
Other audio scraping libraries allow users to set YouTube request headers such as `cookie` and `x-youtube-identity-token`.
[Here's an example of this with node-ytdl-core.](https://github.com/fent/node-ytdl-core/blob/master/example/cookies.js) The purpose of that is to prevent 429s from happening as often.
Could Lavaplayer also do this? `cookie` header could be passed to any request, and `x-youtube-identity-token` to YT requests.
It would be nice to have more defense against 429s, especially from YouTube, who seems to be getting more aggressive about this.

**Comment by sedmelluq** [comment]
You already can, either via `source.getMainHttpConfiguration().setHttpContextFilter(...)` or if you use the rotator, in its setup, do `setup.withMainDelegateFilter(...)` before calling the setup method. Keep in mind that non-search filter should either extend `YoutubeHttpContextFilter` and call `super`, or delegate to it, and search one should not.

**Comment by redbrain** [comment]
Thank you!
