### ISSUE TITLE
Playlist load

### ISSUE THREAD

**Issue by x1Tapx** [sedmelluq/lavaplayer#575]
If a playlist is available, none can be found or a song is played that is not in the playlist at all.
![Debug Lavaplayer](https://user-images.githubusercontent.com/54123553/103907077-18556980-5101-11eb-8663-dc2375987590.PNG)

**Comment by x1Tapx** [comment]
Only one track will be loaded but the playlist has 223 entrys

**Comment by MCOfficer** [comment]
please share the code of your `playlistLoaded` method as well as your LP version.

**Comment by x1Tapx** [comment]
`        for (AudioTrack audioTrack : audioPlaylist.getTracks()) {
            musicController.getQueue().addSong(audioTrack, textChannel);
            if (musicController.getAudioPlayer().getPlayingTrack() == null) musicController.getAudioPlayer().playTrack(audioTrack);
        }`
        LP version: LATEST

**Comment by MCOfficer** [comment]
there is no  `audioTrack` parameter in `playlistLoaded`, so this must be a mistake. Just share the entire method, including the head.

For the record, `LATEST` is deprecated for a reason and should not be used. Use a fixed version instead. The latest version number can be found at the top of the README.

**Comment by x1Tapx** [comment]
but why is there a method called **audioPlaylist.getTracks()**?

**Comment by sedmelluq** [comment]
Seems to load just fine for the URL in original post.

![image](https://user-images.githubusercontent.com/16945769/106334484-6fc79f00-6293-11eb-95f7-2490f6203a57.png)

Must be an issue with the way you are queueing them.
