### ISSUE TITLE
Only short YouTube links are working

### ISSUE THREAD

**Issue by Nick-kel** [sedmelluq/lavaplayer#580]
If I want to play a song using a YouTube link, the long link (e.g. https://www.youtube.com/watch?v=dQw4w9WgXcQ) does not work. Only the short link (e.g. https://youtu.be/dQw4w9WgXcQ) is working

**Comment by MCOfficer** [comment]
Please provide your LP version.

Also clarify how it's not working, f.e. the error message in the logs.

**Comment by Nick-kel** [comment]
Version: 1.3.67
There's no error, if I'm using AudioPlayerManager#loadItemOrdered and the track url is a playlist, it runs the noMatches methode

**Comment by sedmelluq** [comment]
Unable to reproduce.

**Comment by Nick-kel** [comment]
@sedmelluq please look at https://github.com/Nick-kel/LupoBot/blob/master/lupobot-plugins/lupobot-plugin-music/src/main/java/de/nickkel/lupobot/plugin/music/commands/PlayCommand.java in line 35 https://github.com/Nick-kel/LupoBot/blob/master/lupobot-plugins/lupobot-plugin-music/src/main/java/de/nickkel/lupobot/plugin/music/lavaplayer/MusicServer.java and line 45

**Comment by MCOfficer** [comment]
You may want to update to 1.3.71. I cannot recall seeing this problem in the changelog, but it's worth a shot.

**Comment by Nick-kel** [comment]
[Updated](https://github.com/Nick-kel/LupoBot/commit/bb5244a609e3b502f99f7eab21ae358e4f3190dc) the dependency and tested it. This issue still exists

**Comment by sedmelluq** [comment]
Still unable to reproduce.
