### ISSUE TITLE
Something of wrong on LIVE

### ISSUE THREAD

**Issue by SuperKali** [sedmelluq/lavaplayer#583]
![Screenshot_3](https://user-images.githubusercontent.com/19473898/107943199-a2101680-6f8c-11eb-9a61-2158026759a9.png)

After updating I got this error with live-streaming.

Thanks in advice.

**Comment by MCOfficer** [comment]
can you post the audio track in question?

Also, you can update to 1.3.71.

**Comment by SuperKali** [comment]
The audio track is a live stream https://radio.superkali.me/radio/8000/audio.mp3

I will try with the new update.

Thanks for your time.

**Comment by MCOfficer** [comment]
That URL works for me on 1.3.55. Either this is a regression, or there's something fishy going on between you and their site, for example might have banned your IP.

**Comment by SuperKali** [comment]
Yes, for me works but when the live is playing after tot minutes the live crashes.

Idk i retrying again with the new update

**Comment by SuperKali** [comment]
@MCOfficer Seems that is fixed on the latest version, thanks so much for your support and time 👍
