### ISSUE TITLE
Youtube Track loading but not playing in Discord

### ISSUE THREAD

**Issue by ReikoTigon** [sedmelluq/lavaplayer#587]
As the title says :D

Atm i don't have a queue. That means if I get a playlist I directly start the first track track from the playlist.
If it's a solo song I start it directly.

The command I am using is: `audioPlayer.startTrack(track, true)` and `startTrack(playlist.tracks[0], true)`

I call them directly from the Events (`playlistLoaded(playlist: AudioPlaylist)` and `trackLoaded(track: AudioTrack)`)
The `onTrackStart() `gets called too, as does the `onTrackEnd()` after a few seconds with the AudioTrackEndReason "CLEANUP"

I am using LavaPlayer-Version 1.3.71 and JDA-Version 4.2.0_227 (And mostly Kotlin)
Propably duplicate of: #568 (Has no fix)

**Comment by ReikoTigon** [comment]
Propably duplicate of: #568 (Has no fix yet)

**Comment by sedmelluq** [comment]
`CLEANUP` means you are not polling the player.
