### ISSUE TITLE
Livestream/Radio crashes after 7h

### ISSUE THREAD

**Issue by DaliborTrampota** [sedmelluq/lavaplayer#594]
Hello, 

One user opened this issue on lavalink https://github.com/Frederikam/Lavalink/issues/447 and it happened to me as well but he was playing youtube livestream and I was playing upbeat radio. I wanted to reproduce the error today again and see what it logs in lavalink log because I forgot to check the log last time but this time it wasn't even 7h and it crashed -> https://sourceb.in/xhJVhYOOHv

**Comment by DaliborTrampota** [comment]
Dead. Closing.

**Comment by MCOfficer** [comment]
Does the issue not appear anymore, or why would you close this?

**Comment by DaliborTrampota** [comment]
Because nobody responded to it and doubt somebody will. It isn't important there are way more important issues for example bot not outputting audio but no error in logs and song is playing based on player status. Besides I'm working on my own music player.

**Comment by MCOfficer** [comment]
Well it didn't go away, so i see no reason not to keep it open until sed finds time to look at it. Certainly doesnt hurt.

**Comment by DaliborTrampota** [comment]
Does it occur to you? Because not to me anymore now it can't even output audio for 7h straight

**Comment by MCOfficer** [comment]
It doesn't, but i assumed you hadn't been trying to reproduce it. If you have but simply haven't been able to, ignore me.

**Comment by DaliborTrampota** [comment]
Different issue occurs before you can even replicate the old error. And to be honest i don't care anymore. If he didn't have time in those 5 months to write a simple message I doubt he'll have time to write a piece of code. I'd do it myself but java is big no no. I closed it along with other issues I opened because none of them had a single response and they were just showing in the github app and I was tired hoping for answers. If its closed I can close my hopes with it.
