### ISSUE TITLE
Error while loading.

### ISSUE THREAD

**Issue by Xireu0** [sedmelluq/lavaplayer#595]
Hello, I recently found my old music bot, I launched it on my server and from now on the music I add from youtube doesn't work, it always crashes some error, unfortunately I can't put a staktrace. If anyone has enough time to download my project, build it, fire up and check how it works.

totorial:
1. join the vice channel
2. use command
/music join - bot join to the voice channel
3. use command 
/music play - this command adds youtube music to the queue

/music add url  - does the same as /music play but a link to the music is provided here!

link for source code project: https://www.mediafire.com/file/0u6wuwsg7htylh5/dcbot.rar/file

Please let me know what has changed because I have not been able to come to this since yesterday ...

**Comment by MCOfficer** [comment]
Update lavaplayer, big time. Online services are always in flux, so if a library and/or program doesn't work anymore, you should always look for updates first.

**Comment by sedmelluq** [comment]
If you still have a problem with the latest version, make an issue with a stacktrace included.
