### ISSUE TITLE
missing PLAYER_JS_URL

### ISSUE THREAD

**Issue by caneleex** [sedmelluq/lavaplayer#597]
hey, a few days ago i got this error when trying to load a track. however, i got it once in like 20+ times, so i guess it's not easily reproducible.

i was running version 1.3.72, and i don't think 1.3.73 would fix it.

log: https://mlnr.dev/up/log.log (it's too long for haste services)

**Comment by evilduck95** [comment]
Not sure if anybody else has mentioned this, but thought it would be worth me saying. 
Tracks that produce this error can be played if you search for them.

**Comment by SuperKali** [comment]
Hi, i've the same problem.

![image](https://user-images.githubusercontent.com/19473898/113201121-778eca00-9269-11eb-8f64-1225e5ec2edc.png)
![image](https://user-images.githubusercontent.com/19473898/113201162-81183200-9269-11eb-8bf7-8422d85af495.png)

**Comment by SuperKali** [comment]
I've tried another version of lava player and works, IDK what is the problem.

I'm checking the version that works.

**Comment by SuperKali** [comment]
Nothing, works but if i upload the version on another bot stop to working again.

**Comment by caneleex** [comment]
the issue is likely a cookies consent window that basically breaks LP's parsing. also, if you have the same issue, there's no need to send the same logs

**Comment by upedd** [comment]
Is there any fix?

**Comment by EvieePy** [comment]
Can confirm this is happening to many wavelink users. (Including myself)

Java 13
Ubuntu 20.04
Lavaplayer: 1.3.73

**Comment by SuperKali** [comment]
Some of my discord bots doesn't work, if there's a temporary solution, please notice us.

**Comment by Jourdelune** [comment]
yes, it prevents my bot from working in the same way following this problem

**Comment by DragosDAS** [comment]
same here.

**Comment by caneleex** [comment]
this should be fixed in 1.3.74, closing

**Comment by PredaaA** [comment]
The fix of 1.3.74 fixed it for 10mins for me, then it burned again with the same error.
