### ISSUE TITLE
Lavaplayer starts to lag after a few seconds

### ISSUE THREAD

**Issue by claude-6969** [sedmelluq/lavaplayer#601]
Hi, i'm using lavaplayer with JDA and the audio starts lagging after a few seconds. The lag is so noticable its like every second frame is missing. There are no errors in the console. Any fix?

**Comment by claude-6969** [comment]
Also i have plenty or RAM and bandwidth free.

**Comment by claude-6969** [comment]
So i tired version `1.3.69` and everything is working smoothly.

**Comment by MCOfficer** [comment]
- How is your CPU doing? Also, what source are you playing from, and do you have audio transformations (f.e. volume changes)?
- Bandwidth is one thing, but it could also be package loss on the way to discord. One way to check that is to ping discord via `mtr`.
- What version did you have problems with? if it's newer than 1.3.69, please reopen the issue, as there may be a regression.

**Comment by claude-6969** [comment]
Playing from youtube, 75% of my cpu is free.
When talking with my friends the voice is smooth and the ping is good.
I just randomly changed my version to `1.3.69` and its working but it wasn't working with `1.3.73` and `1.3.72`

**Comment by claude-6969** [comment]
> What version did you have problems with? if it's newer than 1.3.69, please reopen the issue, as there may be a regression.
ok

**Comment by MCOfficer** [comment]
Can you also try 1.3.70? This *may* be related to bc7f5517f2b0847cfe45790633ab204d8c811031; if it is, 1.3.70 should also have this problem.

**Comment by claude-6969** [comment]
`1.3.70` also have this problem.

**Comment by claude-6969** [comment]
So i changed the channel bitrate from 96 kbps to 64 kbps and everything is running good, Even with `1.3.70` wtf?

**Comment by claude-6969** [comment]
![image](https://user-images.githubusercontent.com/69721864/112508324-40c03c00-8db1-11eb-8ebb-3a1cfefdfa9e.png)
LMFAO

**Comment by claude-6969** [comment]
So the problem was the packet loss. It was fixed when i started my bot on AWS.

**Comment by Kifo1** [comment]
Is there any solution for this problem without a server?
