### ISSUE TITLE
Lavaplayer 1.3.73 Unable to load youtube playlists

### ISSUE THREAD

**Issue by NachtRaben** [sedmelluq/lavaplayer#602]
Today across various bots and lavalink instances we are unable to load any youtube playlists.

https://www.youtube.com/playlist?list=PLPThSYCXh4Qup8-INBjKQz7qNik6WEaFN
https://www.youtube.com/watch?v=jzebNpYZMgU&list=UUMOgdURr7d8pOVlc-alkfRg&index=2

Armadeus Lavalink - https://hastebin.de/ipedobefal.apache
Armadeus LavalinkClient - Yes I'm aware this is outdated - https://hastebin.de/latudotimi.yaml
KittyBot URL1 - https://hastebin.de/yopucalako.apache
KittyBot URL2 - https://hastebin.de/ovumifuzul.apache

**Comment by PredaaA** [comment]
I've been seeing those for a few days already, here's some that I gathered. https://pastebin.com/4nQXQ2uN

> https://www.youtube.com/watch?v=oFvQFCl0PZA&list=PLtuDHaqeIA79mRHwe01p8cE-Lq_bopsmZ&index=4&ab_channel=DaleDuroBeats
> https://youtube.com/playlist?list=PLH2KgPdIWtj5V6KevCLCDgpot54spn5aK
> https://www.youtube.com/playlist?list=PLPThSYCXh4Qup8-INBjKQz7qNik6WEaFN
> https://youtube.com/playlist?list=PLE59WSVvT9LqBLsngdHA56Qh-k4m0-qvB

**Comment by MCOfficer** [comment]
> 1 unavailable video is hidden

So some videos just can't be loaded for one reason or another, and LP is choking on that.
