### ISSUE TITLE
1.3.74 Not Working well "Bot joins the room and doesn't play anything

### ISSUE THREAD

**Issue by Abdelaziz17** [sedmelluq/lavaplayer#607]
I'm not getting any issues in gui or log 
i tried older versions too .. but the new version worked for while and stopped again .

The problem with all youtube tracks urls & query's 

I Hope anyone can help ! :D

**Comment by MegasusBMS** [comment]
Same problem

**Comment by zezodfaa** [comment]
> Same problem

Try it on Windows while they finished their updates

**Comment by TOTHT0MI** [comment]
I have the same issue, but I'm interested in how can you access 1.3.74, I cannot find it on the repository. Even though the project page says the latest is 1.3.74 it's nowhere to be found on center. Do I need to download it and use it in the local repo? (I'm stuck at 1.3.73 btw)

**Comment by Abdelaziz17** [comment]
i guess it's solved now on V 75

**Comment by N-Silbernagel** [comment]
@TOTHT0MI jCenter does not accept new versions anymore. New versions are on jitpack

**Comment by RakSrinaNa** [comment]
Jcenter stopped getting new releases, though .75 is published on here.

Personally I had to use
```
maven{
        url = uri("https://dl.bintray.com/sedmelluq/com.sedmelluq")
    }
```
as a repository instead of `jcenter()` for it to find it.

But yeah in the long run will need a solution for jcenter sunsetting, but this is discussed in another issue.

**Comment by Abdelaziz17** [comment]
> Jcenter stopped getting new releases, though .75 is published on here.
> 
> Personally I had to use
> 
> ```
> maven{
>         url = uri("https://dl.bintray.com/sedmelluq/com.sedmelluq")
>     }
> ```
> 
> as a repository instead of `jcenter()` for it to find it.
> 
> But yeah in the long run will need a solution for jcenter sunsetting, but this is discussed in another issue.

After using it for while the bots joins again and don't play anything ...

**Comment by MCOfficer** [comment]
"doesn't playing anything" is unfixable without an error or stacktrace.

**Comment by tomkeuper** [comment]
I had the same problem and with no error or stacktrace at all. But after some issues with updating to 1.3.75 it worked again. Only problem that i cant really update my old bot so its broken for now until I can release an update.

**Comment by sedmelluq** [comment]
Refer to this next time before reporting a "no error" issue:
https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md#a7c7989f
