### ISSUE TITLE
Something broke when playing the track

### ISSUE THREAD

**Issue by MegasusBMS** [sedmelluq/lavaplayer#608]
I was on FAQ -> Section Does not work and no exceptions -> AudioEventAdapter#onTrackException

Here is the error:

FINISHED Something broke when playing the track.LOAD_FAILED

>>If i try a single track never work
>>if i try a playlist may be a chance to work just some traks from playlist
>>if i try to play those tracks witch work in playlist don't work
>>if i try a playlist witch start with those tracks don't work

Also i had the same problem more times , but it resolved when i was updating the version of lavaplayer , but now i have version 1.3.73.

Maven and Grandle don't find 1.3.74 and 1.3.75

**Comment by RakSrinaNa** [comment]
I had to use 
```
    maven{
        url = uri("https://dl.bintray.com/sedmelluq/com.sedmelluq")
    }
```
instead of `jcenter()` for it to find the latest releases.

**Comment by MegasusBMS** [comment]
Cheers!!!
