### ISSUE TITLE
New Youtube cookie consent screen causing errors

### ISSUE THREAD

**Issue by yummypasta** [sedmelluq/lavaplayer#611]
It seems that pretty recently ([articles point to April 1](https://www.ghacks.net/2021/04/01/here-is-the-easiest-way-to-get-rid-of-googles-before-you-continue-to-youtube-prompt/) for when this started happening), Youtube started showing users a cookie consent page, which LavaPlayer does not know how to handle.

I was made aware of this from [an issue](https://github.com/yummypasta/MinecraftManhunt/issues/65) in my project that depends on LavaPlayer. From what I could get out of the logs submitted, the error `no PLAYER_JS_URL in youtube root` was being printed. I copied the html printed in the logs into a [file](https://github.com/sedmelluq/lavaplayer/files/6253394/lavaplayer_error.html.txt) and opened it in my browser, and I got a page looking something like this:

<img width="473" alt="Screen Shot 2021-04-03 at 2 02 40 PM" src="https://user-images.githubusercontent.com/12377772/113491390-44288700-9485-11eb-8120-6c6e1bdfacc6.png">

Also in the logs was the URL `consent.youtube.com`, which the "OK" button redirects to, and was also mentioned in the article linked above.

---
### Additional Info
- This error occured with LavaPlayer version `1.3.59`, but since 1) the error reportedly only started in the last few days, 2) articles point to this being a new occurrence, and 3) I did not see anything in commit history since 1.3.59 that would address this, I believe this would still happen on the latest version. 
- I tried to reproduce this error on my local machine, and everything worked fine. I think Youtube is slowly rolling this page out to select users, or possibly users in specific regions.

Thanks in advance!

**Comment by RakSrinaNa** [comment]
#597 should be fixed in recent versions
