### ISSUE TITLE
Direct MP3 Files' URLs 127 Characters or More Do Not Fire TrackStartEvent

### ISSUE THREAD

**Issue by FireController1847** [sedmelluq/lavaplayer#614]
I originally reported this issue over at Lavalink, but it appears this may go deeper than I imagined. https://github.com/freyacodes/Lavalink/issues/476

We boiled it down to this: Playing an MP3 file directly from the URL will not fire the TrackStartedEvent if it is 127 characters or more longer. This can be a problem for services where they require a token to unlock the MP3 file.

Example:
The following URL fires the TrackStartedEvent (126 characters):
```
https://filesamples.com/samples/audio/mp3/sample3.mp3?abcdefg=5&AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```
The following does not (127 characters):
```
https://filesamples.com/samples/audio/mp3/sample3.mp3?abcdefg=5&AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

I wonder if this may tie into a possible deeper issue or if it is just affecting the TrackStartedEvent. Does Lavalink use a byte for storage anywhere? Any byte limitations? I'd be willing to take a shot at fixing this in the source, but I've never worked here so I may need some pointers as to what to pay attention to.

Here is my Lavalink log file, if that helps. If you need any more information let me know and I will try my best to get it to you
[spring.log](https://github.com/freyacodes/Lavalink/files/6330943/spring.log)

**Comment by MCOfficer** [comment]
Just to be clear: does the file not play at all and is just silently swallowed, or does everything work *but* the event isn't fired?

**Comment by FireController1847** [comment]
Everything works fine, the event just isn't fired, at least from what it appears

**Comment by FireController1847** [comment]
I have confirmed that when working directly with the Lavaplayer source this issue does not occur. I went to Lavalink and found I was unable to reproduce it there. I will be closing this issue as I believe it has to do with the library I am using to add C# compatibility.
