### ISSUE TITLE
no PLAYER_JS_URL in youtube root EID

### ISSUE THREAD

**Issue by 4l3xand3r** [sedmelluq/lavaplayer#617]
I get this error when I input YouTube links. YouTube seems to have removed the PLAYER_JS_URL
![grafik](https://user-images.githubusercontent.com/44643285/115548330-a667f100-a2a7-11eb-9ed3-3bbdcf7804d0.png)

**Comment by MCOfficer** [comment]
#597

Please share your entire stacktrace next time.

**Comment by maanisim** [comment]
Please close this issue as it's been over a year and the logs were not provided.
