### ISSUE TITLE
Soundcloud links not working

### ISSUE THREAD

**Issue by Bob-Joe-2000** [sedmelluq/lavaplayer#625]
Could not play: Unknown file format.

**Comment by MCOfficer** [comment]
Please post a stacktrace.

**Comment by Bob-Joe-2000** [comment]
comes from 

@Override
 public void loadFailed(FriendlyException exception) {
        System.out.println(exception.getMessage())
}

Output is either: 
Could not play: Unknown file format.
Could not play: This url does not appear to be a playable track.

There is no error output, it just prints an exception, that is the whole message

**Comment by Bob-Joe-2000** [comment]
I was using version 1.3.55
Just upgraded to 1.3.75 and now it works
