### ISSUE TITLE
Doesn't work for linux (Centos 7)

### ISSUE THREAD

**Issue by MrEAlderson** [sedmelluq/lavaplayer#63]
It says that it's working but nothing is happening.
There are no errors

**Comment by the-nick-dev** [comment]
Had some issue with Linux and lavaplayer, in currently recoding the whole project, gonna check i I will implement music

**Comment by MrEAlderson** [comment]
After some while I've received this error

> [23:23:46] [WARN] [net.dv8tion.jda.core.audio.AudioWebSocket]: Failed to establish websocket connection: SOCKET_CONNECT_ERROR - Failed to connect to 'us-central21.discord.gg:443': Die Wartezeit für die Verbindung ist abgelaufen (Connection timed out)

**Comment by napstr** [comment]
The provided log is a network issue (fix your network) reported by JDA. Why was this issue opened in lavaplayer?

**Comment by MrEAlderson** [comment]
Because the bot working is working just fine but he's not saying anything

**Comment by napstr** [comment]
Your issue does not appear to be a lavaplayer issue, but either an issue with your network (likely if occasional) , your code (likely if always failing), or the discord api lib (JDA) you are using (unlikely).

**Comment by sedmelluq** [comment]
No response, closing. Reopen if still a problem.

**Comment by tokyodaito** [comment]
The problem exists. I don't understand how to fix it
