### ISSUE TITLE
status UNPLAYABLE

### ISSUE THREAD

**Issue by 89z** [sedmelluq/lavaplayer#646]
Based on this code:

https://github.com/sedmelluq/lavaplayer/blob/707771af705b14ecc0c0ca4b5e5b6546e85f4b1c/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/youtube/DefaultYoutubeTrackDetailsLoader.java#L215-L222

I made this request:

~~~
https://www.youtube.com/get_video_info?video_id=Cr381pDsSsA&
eurl=https://youtube.googleapis.com/v/Cr381pDsSsA&hl=en_GB&html5=1&c=ANDROID&
cver=16.24&sts=18823
~~~

but I get this result:

~~~json
"playabilityStatus":{"status":"UNPLAYABLE",
"reason":"Playback on other websites has been disabled by the video owner."
~~~

**Comment by MCOfficer** [comment]
am i mistaken, or is this not a lavaplayer bug? if it isn't, it doesn't really belong on this bugtracker. You might find support on the JDA discord, in the #lavaplayer channel.

**Comment by 89z** [comment]
how is it not a LavaPlayer bug? I literally quoted from the LavaPlayer source code...

**Comment by MCOfficer** [comment]
Ah. I read it as if it was a manual request, based on LP's code.

**Comment by 89z** [comment]
LP code is resulting in UNPLAYABLE response, which means any manual requests derived from LP code will also result in UNPLAYABLE response.

Do you have any evidence that LP code will result in "OK" response with the video in question?

**Comment by 89z** [comment]
Looks like certain videos require authentication. I have a YouTube OAuth implementation here (in another language) if it helps:

https://github.com/89z/mech/blob/v1.20.3/youtube/oauth.go
