### ISSUE TITLE
Native support for Audio Streams like AudioInputStream or TargetDataLine/SourceDataLine

### ISSUE THREAD

**Issue by MwenDavo** [sedmelluq/lavaplayer#655]
I'm developing a discord bot that takes music from spotify in the format of a Byte[] and plays it directly to a Discord channel (when the bot is connected to it). The problem is I'm finding it extremely difficult to achieve this due to the lack of support for this kind of content from the library. I've tried creting my own AudioSourceManager, but I can't create the correct AudioTrack for the music. I support for this kind of format should be supported natively.

**Comment by MCOfficer** [comment]
The purpose of this library is to take a URI (youtube, soundcloud, file, etc) and give you an AudioStream of some sort, for example, in the form of a stream of ByteBuffers.

If you already have an AudioInputStream, then you don't need LP, just plug that into your output.

**Comment by MwenDavo** [comment]
I'm following the Discord4J guide on how to make a music bot, and it recommended using lavaplayer due to native integration with discord audio codec. If I understand correctly, I can input my own AudioStream directly to the PlayerManager class?
I've looked a bit and found that the way the Discord4J guide suggests the ingest of audio is throught the MutableAudioFrame class, that stores the ByteBuffer. If I create a MutableAudioFrame with my own ByteBuffer using the Byte[] from the Spotify API it should theoretically work, right?

**Comment by MCOfficer** [comment]
> 
> 
> I'm following the Discord4J guide on how to make a music bot, and it recommended using lavaplayer due to native integration with discord audio codec. If I understand correctly, I can input my own AudioStream directly to the PlayerManager class?
> I've looked a bit and found that the way the Discord4J guide suggests the ingest of audio is throught the MutableAudioFrame class, that stores the ByteBuffer. If I create a MutableAudioFrame with my own ByteBuffer using the Byte[] from the Spotify API it should theoretically work, right?

Frankly, i'm the wrong person to ask. You might get more help from the people at D4J, or on stackoverflow (the question seems abstract enough). But it seems unnecessarily complicated to use LP only to convert one type of audio stream into another.

**Comment by MwenDavo** [comment]
Anyway, thanks for the help. I've left an issue on the D4J github, so if anything that's related to lavaplayer happens (or if I manage to accomplish this), I'll reopen this issue and post the news.
