### ISSUE TITLE
Frequently skips songs halfway through and fails to load songs (http links)

### ISSUE THREAD

**Issue by Fridgey** [sedmelluq/lavaplayer#66]
Constantly getting errors like this: https://hastebin.com/raw/iwanerakur

There is absolutely nothing wrong with the audio file. It plays fine in my browser, so I can only conclude that there is something wrong with this library.

**Comment by FlashOnFire** [comment]
We can't see your error, use http://pastebin.com instead of hastebin

**Comment by sedmelluq** [comment]
Report details inaccessible.
