### ISSUE TITLE
Can't play songs because of 400 Bad request

### ISSUE THREAD

**Issue by JeremyStarTM** [sedmelluq/lavaplayer#664]
I am running LavaPlayer 1.3.77 and followed the [Discord4j Musicbot Tutorial](https://discord4j.readthedocs.io/en/latest/Music-Bot-Tutorial/). I am done with that tutorial now, but when I try to play some music, this comes (some things are german, but they aren't essential for the report):
[(Click here for Paste on paste.ubuntu.com)](https://paste.ubuntu.com/p/zTc5M38WWW/)

If you need to have my classes or such stuff, write a comment with it and I post it :D
Thanks in advance!

**Comment by MCOfficer** [comment]
Can you provide a URL that triggers this?

Also try to reproduce on the latest version, 1.3.78

**Comment by JeremyStarTM** [comment]
What do you mean by that? It triggers on every YouTube URL. I haven't tested it with other websites yet. Also, I am now running 1.3.78 but the error still occures

**Comment by JeremyStarTM** [comment]
Closing this as I'm not working on the project anymore and this issue is inactive.
