### ISSUE TITLE
Next queued track won't start

### ISSUE THREAD

**Issue by MillzyDev** [sedmelluq/lavaplayer#670]
When a track ends, LavaPlayer doesnt play the next one queued. Im not sure what the cause is, but it started happening when I added stuff to my `nextTrack` method to add "now playing" stuff, i've added some logging stuff to the `onTrackEnd` overrided method, but nothing logs so i can only assume that it doesnt get called what so ever 
```java
    public void nextTrack() {
        AudioTrack track = player.getPlayingTrack();
        new Response()
                .setColour(Color.ORANGE)
                .setTitle("Now Playing")
                .setMessage(String.format("[%s](%s)", track.getInfo().title, track.getInfo().uri))
                .sendResponse(channel);

        Logger.info(String.format("Now playing %s by %s", track.getInfo().title, track.getInfo().author));
        player.startTrack(queue.poll(), true);
    }

    @Override
    public void onTrackEnd(AudioPlayer player, AudioTrack track, AudioTrackEndReason endReason) {
        if (endReason.mayStartNext) {
            nextTrack();
            Logger.info("Starting next track");
        } else {
            Logger.info("Unable to start next track, end reason was " + endReason.name() + "and value of mayStartNext is " + endReason.mayStartNext);
        }
    }
```
here are both the methods, i've pushed the rest to the projects github page (https://github.com/MillzyDev/SynthWave/tree/main/src/main/java/dev/millzyg/SynthWave) if you need any more, what's above is in `TrackScheduler.java`

**Comment by confusedkernel** [comment]
hi, i'm encountering the same problem and I see that you've closed the issue, did you find any solution to it?

**Comment by MCOfficer** [comment]
> hi, i'm encountering the same problem and I see that you've closed the issue, did you find any solution to it?

This part is generally your code, so there's no telling if their problem was the same as yours. If you need support, i'd recommend asking in the [JDA Server](https://discord.gg/0hMr4ce0tIk3pSjp), #lavaplayer channel.
