### ISSUE TITLE
TwitchSourceManager not Working

### ISSUE THREAD

**Issue by derfurkan** [sedmelluq/lavaplayer#677]
Hallo i want to use the TwitchSourceManager so i registered it and gave the right Identifier (https://twitch.tv/Faker) The `getChannelIdentifierFromUrl` Method converts this to "Faker". The Problem is now that Lavaplayer shows me a "no machtes" Error. Ive also configured my own Twitch Cliend API Key. This also didnt work. So how am i supposed to use this?

**Comment by MCOfficer** [comment]
#662 - what you can do now is switch to an active fork, f.e. https://github.com/Walkyst/lavaplayer-fork
