### ISSUE TITLE
AudioEventAdapter fire same multiple event

### ISSUE THREAD

**Issue by Miloune** [sedmelluq/lavaplayer#68]
Hello,

I'm using lavaplayer with JDA, and it looks like onTrackEnd event is fired multiple time in a row for the same track end.

I'm doing something wrong with these call?

> 2017-10-27 23:09:20,552 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:82] Track [**tracktTitle**] ended [STOPPED]
2017-10-27 23:09:21,473 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:82] Track [**tracktTitle**] ended [STOPPED]
2017-10-27 23:09:24,642 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:82] Track [**tracktTitle**] ended [STOPPED]

(Don't mind about second, i was in debug)

```
/**
     * Start the next track, stopping the current one if it is playing.
     */
    public boolean nextTrack() {
        // Start the next track, regardless of if something is already playing or not. In case queue was empty, we are
        // giving null to startTrack, which is a valid argument and will simply stop the player.
        LOGGER.debug("Play next track");
        return this.player.startTrack(this.queue.poll(), false);
    }
```

    /**
     * Start the next track, if none track, play the last track.
     */
    public void nextTrack(AudioTrack lastTrackPlayed) {
        final boolean isNextTrackStart = nextTrack();
        if (isNextTrackStart) {
            return;
        }
        LOGGER.debug("No more track in the queue, replay the last one");
        this.player.startTrack(lastTrackPlayed.makeClone(), false);
    }

   ```
@Override
    public void onTrackEnd(AudioPlayer player, AudioTrack track, AudioTrackEndReason endReason) {
        LOGGER.debug("Track [{}] ended [{}]", track.getInfo().title, endReason.name());
        // Only start the next track if the end reason is suitable for it (FINISHED or LOAD_FAILED)
        if (endReason.mayStartNext) {
            nextTrack(track);
        }
    }
```

The problem is, when i add two tracks. The first one is played, then when it's end, the second probably start to play(?) and is removed from the queue, then the event is fired again, and now it play the last music since there is no more track in queue, so it play the first one.

Hope you understand my problem!

Thanks in advance.

PS: More logs to explain it

> 2017-10-27 21:29:05,488 DEBUG c.s.d.l.c.m.MatroskaAudioTrack [MatroskaAudioTrack.java:70] Starting to play track with codec A_OPUS
> 2017-10-27 21:32:19,922 DEBUG c.s.d.l.t.p.LocalAudioTrackExecutor [LocalAudioTrackExecutor.java:92] Playing track RqcjBLMaWCg finished or was stopped.
> 2017-10-27 21:32:19,924 DEBUG c.s.d.l.p.AudioPlayer [AudioPlayer.java:290] Firing an event with class TrackEndEvent
> 2017-10-27 21:32:19,925 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:77] Track David Guetta ft Justin Bieber - 2U (The Victoria?s Secret Angels Lip Sync) ended [FINISHED]
> 2017-10-27 21:32:19,925 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:59] Play next track
> 2017-10-27 21:32:19,925 DEBUG c.s.d.l.p.AudioPlayer [AudioPlayer.java:290] Firing an event with class TrackStartEvent
> 2017-10-27 21:32:19,925 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:86] Track is starting [206000] [Rudimental - Sun Comes Up feat. James Arthur [Official Video]]
> 2017-10-27 21:32:19,926 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:86] Track is starting [206000] [Rudimental - Sun Comes Up feat. James Arthur [Official Video]]
> 2017-10-27 21:32:19,926 DEBUG c.s.d.l.t.p.LocalAudioTrackExecutor [LocalAudioTrackExecutor.java:85] Starting to play track qZVm-2nM0sA locally with listener com.sedmelluq.discord.lavaplayer.player.AudioPlayer@676ad0a5
> 2017-10-27 21:32:19,927 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:77] Track David Guetta ft Justin Bieber - 2U (The Victoria?s Secret Angels Lip Sync) ended [FINISHED]
> 2017-10-27 21:32:19,927 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:59] Play next track
> 2017-10-27 21:32:19,927 DEBUG c.s.d.l.t.p.LocalAudioTrackExecutor [LocalAudioTrackExecutor.java:135] Requesting stop for track qZVm-2nM0sA
> 2017-10-27 21:32:19,927 DEBUG c.s.d.l.p.AudioPlayer [AudioPlayer.java:290] Firing an event with class TrackEndEvent
> 2017-10-27 21:32:19,928 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:77] Track Rudimental - Sun Comes Up feat. James Arthur [Official Video] ended [REPLACED]
> 2017-10-27 21:32:19,928 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:77] Track Rudimental - Sun Comes Up feat. James Arthur [Official Video] ended [REPLACED]
> 2017-10-27 21:32:19,933 DEBUG c.s.d.l.p.AudioPlayer [AudioPlayer.java:290] Firing an event with class TrackStartEvent
> 2017-10-27 21:32:19,933 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:86] Track is starting [225000] [Cheat Codes - No Promises ft. Demi Lovato [Official Video]]
> 2017-10-27 21:32:19,933 DEBUG f.m.d.h.TrackScheduler [TrackScheduler.java:86] Track is starting [225000] [Cheat Codes - No Promises ft. Demi Lovato [Official Video]]
>

**Comment by sedmelluq** [comment]
The log shows that one event is dispatched but you handle two events. You probably added two listeners to the player.

**Comment by sedmelluq** [comment]
User error and no response within a month, closing.
