### ISSUE TITLE
twitch randomly stopped working

### ISSUE THREAD

**Issue by ToxicMushroom** [sedmelluq/lavaplayer#69]
https://hastebin.com/buxatipihi.lua
When i check the stream link myself it works fine.

**Comment by ToxicMushroom** [comment]
update it only does this somethimes when i rejoin the channel it starts working

**Comment by Frederikam** [comment]
Appears broken on FredBoat as well on `1.2.44`

**Comment by Shredder121** [comment]
#75

**Comment by sedmelluq** [comment]
Fix merged.
