### ISSUE TITLE
raspberry pi can not play live 

### ISSUE THREAD

**Issue by thedtvn** [sedmelluq/lavaplayer#695]
**sys info:**
jdk: 
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Debian-1deb11u1, mixed mode, sharing
jda : 5.0.0-alpha.9
lavaplayer : 1.3.75

raspberry pi info:

Model		: Raspberry Pi 4 Model B Rev 1.5
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

*no error log 
![image](https://user-images.githubusercontent.com/80153297/170431383-a56a6322-e9ae-4942-81d6-b30d730a6266.png)

![image](https://user-images.githubusercontent.com/80153297/170430458-4a92503a-4655-45ac-a7be-c6a01a17e355.png)

**Comment by thedtvn** [comment]
*it work in Windows 10
jdk 17

**Comment by thedtvn** [comment]
*update : it auto skip :\

**Comment by tokyodaito** [comment]
I have the same problem with CentOs 7. The problem is that lavaplayer uses its own decoders. Try installing another operating system not using Linux x86-64, only compatible with libc, not with musl (Alpine uses musl)
