### ISSUE TITLE
"libconnector.so: dlopen failed: 'libstdc++.so.6' not found" UnsatisfiedLinkError

### ISSUE THREAD

**Issue by metroite** [sedmelluq/lavaplayer#697]
Lavaplayer fails when trying to detect audio files using the native libconnector.so on Termux (Aarch64, Linux, Android). There are no issues on x86 Windows. I have included the native libraries for Linux Aarch64 using [this repo.](https://github.com/aikaterna/lavaplayer-natives).

A possible issue could be that Termux [uses Bionic instead of GNU libc](https://github.com/termux/termux-packages/issues/2798).

This issue prevents the use of lavaplayer on servers with mobile architecture. Any suggestions?

[crash.txt](https://github.com/sedmelluq/lavaplayer/files/8858073/crash.txt)

**Comment by MCOfficer** [comment]
The same @aikaterna has also compiled a version of libconnector.so with musl: https://cdn.discordapp.com/attachments/485856897677787137/591802067862028298/libconnector.tar.gz

(Mandatory warning, use dodgy links with caution)

**Comment by aikaterna** [comment]
Or you can grab it from https://github.com/aikaterna/lavaplayer-natives/tree/darwin-architecture-split/linux-musl-x86-64/

**Comment by metroite** [comment]
The binaries are compiled for x86-64, is there by any chance one for Aarch64 (ARM)? 
Here is the (to be expected) fail report:
`java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/usr/tmp/lava-jni-natives/1654741505529/libconnector.so: dlopen failed: "/data/data/com.termux/files/usr/tmp/lava-jni-natives/1654741505529/libconnector.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183) (Possible cause: can't load AMD 64 .so on a AARCH64 platform)`

**Comment by aikaterna** [comment]
Can you give https://github.com/aikaterna/lavaplayer-natives/blob/darwin-architecture-split/linux-bionic-aarch64/libconnector.so a try and see how that goes?

**Comment by metroite** [comment]
Amazing! Thank you it works! May I ask for the purpose of learning, did you cross-compile it on a Linux machine with the Android NDK and linked it with Googles Bionic libraries?

**Comment by aikaterna** [comment]
I installed Termux on my phone, found missing build headers for Android, installed all the build tools, edited the build scripts a little to account for some catch-alls that assumed Darwin instead of Android, and kept trying the build scripts until they spit out a dynamic library file. I tested it in a Lavalink.jar running on that Termux session with a clone of the Discord bot I use and it worked (along with the udpqueue native and the timescale/lavadsp native I built for Bionic), but wanted to check with you and make sure it worked in pure lavaplayer (or whatever other application you needed it for).

**Comment by aikaterna** [comment]
One reason why I didn't do it "properly" as you described was that this sort of native file (or a musl-supporting build) can't really be used in lavaplayer or Lavalink until the native loader can programmatically determine the libc flavor used - glibc, musl, and Bionic all build into the `linux-aarch64` or `linux-x86-64` folders without any further naming differences. If you do decide to try a proper build for fun, you can target `aarch64-unknown-linux-android24` or `aarch64-linux-android` for Bionic.

**Comment by metroite** [comment]
Thank you for the detailed explanation! 👍
