### ISSUE TITLE
loadItem won't give any response?

### ISSUE THREAD

**Issue by MrWhiteGoat** [sedmelluq/lavaplayer#7]
Hey, I'm having troubles making loadItem respond to me... It just skips the whole function.

code - https://hastebin.com/atefexahot.java

**Comment by MrWhiteGoat** [comment]
It is being invoked. Though not giving me a response.

**Comment by sedmelluq** [comment]
I remember talking about such a case in Discord, was this the case caused by missing dependencies?

**Comment by MrWhiteGoat** [comment]
@sedmelluq yup. I was 2000 version off.
