### ISSUE TITLE
Twitch doesnt work rn

### ISSUE THREAD

**Issue by KasaiKonoru** [sedmelluq/lavaplayer#708]
Why Twitch livestreams are not working anymore?

**Comment by MCOfficer** [comment]
This repo is pretty much dead, use [Walkyst's  fork](https://github.com/Walkyst/lavaplayer-fork).

**Comment by KasaiKonoru** [comment]
> This repo is pretty much dead, use [Walkyst's fork](https://github.com/Walkyst/lavaplayer-fork).

thanks, but is there also a new lavalink jar for this fork?

**Comment by KasaiKonoru** [comment]
I mean a lavalink with this new lavaplayer fork?

**Comment by MCOfficer** [comment]
Seems like lavalink already uses the fork: https://github.com/freyacodes/Lavalink/blob/6d589165e84903fa6502bdec3aef39851e5afde1/settings.gradle.kts#L43

**Comment by KasaiKonoru** [comment]
okay thx. Does Twitch works for you?
