### ISSUE TITLE
Youtube Master Token Update Failed

### ISSUE THREAD

**Issue by ProfLS** [sedmelluq/lavaplayer#709]
Non-fatal Error while initializing my bot which is based on Aiode.  I'm recieving an error at 

`sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker`

Invalid Status Code for Login Account Response (Err 400)

This is calling the Youtube master token update to fail.  Is it a possible error with my Youtube API setup?  Or is it something wrong with the actual request/fetch function?  Any possible fixes?  Haven't noticed any severe Youtube integration problems, but this error is causing bot to have a sub-standard performance.

**Comment by MCOfficer** [comment]
Without looking too deep into it, consider switching to Walkyst's fork - this repo hasn't seen maintenance for 2 years, which causes it to break frequently over YT changes:

https://github.com/Walkyst/lavaplayer-fork

**Comment by ProfLS** [comment]
Thanks!  Imma do that!
