### ISSUE TITLE
Music Bot keeps connecting and disconnecting from the voice channel after /play command.

### ISSUE THREAD

**Issue by MicheleDiMezzaCutillo** [sedmelluq/lavaplayer#711]
my music bot created in java on intellij with grandle, days ago was running without problems, everything worked! I was able to get all the commands of the bot to work without problems, but today while using it it started giving problems. 
Here's basically what I do and what happens:
I turn on the bot,
I enter a voice channel and do /play <url>,
the bot enters the channel where I am,
in chat he writes the track he should play,
disconnects and reconnects for no reason.

remains active for 3-4 seconds, then disconnects and reconnects immediately.
then I turn it off because it drives me crazy

Any idea? Thanks :)

**Comment by thedarkcolour** [comment]
Also having this issue, would appreciate any news

**Comment by QwertyMo** [comment]
Which version of JDA are you using? Try to use v5.0.0-beta.5 or higher. They fix something with voice connection

**Comment by MicheleDiMezzaCutillo** [comment]
Discord is rolling out a breaking change to audio connections today. Everyone who makes use of audio connections should update to the latest version of JDA. Affected bots will struggle connecting to channels, resulting in join/leave loops.

For people using v5 (recommended), update to 5.0.0-beta.6 or later.
The fix has been backported to v4 (legacy) with 4.4.1_353, however we recommend updating to v5 as soon as possible.

This is a message found on JDA Discord Server today.
