### ISSUE TITLE
Can't find YouTube playlists that are albums

### ISSUE THREAD

**Issue by SmileyFace799** [sedmelluq/lavaplayer#713]
For some reason, album playlists just don't seem to work.
I have the following code:
```java
public void queue(String identifier, String guildId) {
    playerManager.loadItem(identifier, new AudioLoadResultHandler() {
        @Override
        public void trackLoaded(AudioTrack track) {
            queues.get(guildId).queue(track);
        }
    
        @Override
        public void playlistLoaded(AudioPlaylist playlist) {
            for (AudioTrack track : playlist.getTracks()) {
                queues.get(guildId).queue(track);
            }
        }
    
        @Override
        public void noMatches() {
            System.out.println("Couldn't find song");
        }
    
        @Override
        public void loadFailed(FriendlyException e) {
            System.out.println(e.getMessage());
        }
    });
```

This works fine for regular playlists made by users, but for album playlists it can't seem to find a match.
I have tried the following albums, and none of them worked:
- [https://www.youtube.com/playlist?list=OLAK5uy_l6RqWHFaiX0iO8tCHhqcq-KR6iejY-Pvs](https://www.youtube.com/playlist?list=OLAK5uy_l6RqWHFaiX0iO8tCHhqcq-KR6iejY-Pvs) (Identifier: OLAK5uy_l6RqWHFaiX0iO8tCHhqcq-KR6iejY-Pvs)
- [https://www.youtube.com/playlist?list=OLAK5uy_nCa-9hULF8e9-L-HxDpPDiNgB-9mzDXwc](https://www.youtube.com/playlist?list=OLAK5uy_nCa-9hULF8e9-L-HxDpPDiNgB-9mzDXwc) (Identifier: OLAK5uy_nCa-9hULF8e9-L-HxDpPDiNgB-9mzDXwc)
- [https://www.youtube.com/playlist?list=OLAK5uy_mynbKvLCwPeWIXKAw05jbzEPcXvGzK7B4](https://www.youtube.com/playlist?list=OLAK5uy_mynbKvLCwPeWIXKAw05jbzEPcXvGzK7B4) (Identifier: OLAK5uy_mynbKvLCwPeWIXKAw05jbzEPcXvGzK7B4)

I also tried the following user-made playlists, and all of them worked:

- [https://www.youtube.com/playlist?list=PLmRynaTWYuZFfo0ZdU_k1gnkbH1yVzhNz](https://www.youtube.com/playlist?list=PLmRynaTWYuZFfo0ZdU_k1gnkbH1yVzhNz) (Identifier: PLmRynaTWYuZFfo0ZdU_k1gnkbH1yVzhNz)
- [https://www.youtube.com/playlist?list=PLS4jAfE9d3aIYs7RAuBTYRKQH84uW0GC2](https://www.youtube.com/playlist?list=PLS4jAfE9d3aIYs7RAuBTYRKQH84uW0GC2) (Identifier: PLS4jAfE9d3aIYs7RAuBTYRKQH84uW0GC2)

By looking at the IDs of these playlists & albums, the thing that stands out is how user playlists start with `PL...`, while albums start with `OLAK5uy_...`. I tried changing the first part of the album ID to `PL` instead, although then it goes to loadFailed, saying the playlist does not exist.

Any possible fixes for this would be greatly appreciated

**Comment by MCOfficer** [comment]
> Any possible fixes for this would be greatly appreciated

The repo is unmaintained, try your luck at the predominant fork: https://github.com/Walkyst/lavaplayer-fork

**Comment by SmileyFace799** [comment]
Allrighty, I tried using the fork, and the same issue seems to still be present. I created an issue there, in hopes of a fix some day: https://github.com/Walkyst/lavaplayer-fork/issues/91

**Comment by SmileyFace799** [comment]
Ok so I found out why it didn't work for me.

In the readme I read "The identifier is a piece of text that should identify the track for some source. For example if it is a YouTube video ID...", and from this I wrongfully assumed that the identifier had to be the video/playlist ID. It never occurred to me that I could provide the full link for some reason, and playing album playlists does indeed work when I provide the full link.

in conlusion, it does in fact work, I just had a brain fart :P
