### ISSUE TITLE
How Lavaplayer seek YouTube video?

### ISSUE THREAD

**Issue by Fyphen1223** [sedmelluq/lavaplayer#722]

**Comment by Fyphen1223** [comment]
I want to know these things:

1. How lavaplayer seeks
2. How lavaplayer downloads YouTube videos

You guys may think that's obvious, but I'm just a beginner so I want to know.
I appreciate all of your helps.
Thanks,

**Comment by Bu156** [comment]
For the first question, it's as easy as calling `.setPosition(time)` on the track you want to seek in.

As for the second, I'm not immediately sure, but I guess it would be easy to find out by looking into the classes related to YouTube tracks.

**Comment by Fyphen1223** [comment]
Yeah, but your answer is not what I intend.

HOW Lavaplayer seeks audio resource, not how can I seek audio resource.

and second, I'm not good at Java and Kotling, so I'm not sure what can I do.

**Comment by Fyphen1223** [comment]
Ok thanks
