### ISSUE TITLE
How to load a Youtube video using keyword

### ISSUE THREAD

**Issue by Kadnium** [sedmelluq/lavaplayer#73]
Hello! I'm pretty new here.
My bot can play the using a youtube link, but I would like to have it so it can search a video for the youtube video using a user submitted keyword? 
I don't know if this is the right place to ask this but I'll ask it anyway.

**Comment by mailboxkiller** [comment]
YouTube Search: ytsearch:<NAME OF VID> 
Sound Cloud Search: scsearch:<NAME OF SONG>
