### ISSUE TITLE
Youtube search always printing 'Something went wrong when looking up the track'

### ISSUE THREAD

**Issue by StackDoubleFlow** [sedmelluq/lavaplayer#79]
> YoutubeAudioSourceManager sourceManager = new YoutubeAudioSourceManager(true);
>				sourceManager.configureRequests(config ->
>		        RequestConfig.copy(config)
>		                .setCookieSpec(CookieSpecs.IGNORE_COOKIES)
>		                .build());
>				YoutubeSearchProvider provider = new YoutubeSearchProvider(sourceManager);
>				AudioItem item = provider.loadSearchResult("a song");
>				player.playTrack((AudioTrack) item);
this always prints out "Something went wrong when looking up the track" in the console when trying to play any song``

**Comment by StackDoubleFlow** [comment]
bump

**Comment by sedmelluq** [comment]
Please provide the full exception stack trace.

**Comment by sedmelluq** [comment]
No additional details provided within a month, closing.
