### ISSUE TITLE
Error on Startup: ClassNotFoundError

### ISSUE THREAD

**Issue by Andre601** [sedmelluq/lavaplayer#81]
As soon as I try to start my Music-Bot, comes this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sedmelluq/discord/lavaplayer/player/AudioPlayerManager
        at core.Main.addCommands(Main.java:101)
        at core.Main.main(Main.java:70)
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.player.AudioPlayerManager
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more
```

I really have no idea, what exactly isn't working.
I tried to update the maven-dependency, by setting the version to `LATEST` but it didn't fix the issue.

Line 101 in Main.java: 
https://github.com/Andre601/PowerSuggestionBot/blob/master/src/main/java/core/Main.java#L101

Line 70 in Main.java:
https://github.com/Andre601/PowerSuggestionBot/blob/master/src/main/java/core/Main.java#L70

I'm not 100% sure, if I need to add the [AudioEventAdabter](https://github.com/Andre601/PowerSuggestionBot/blob/master/src/main/java/audio/TrackManager.java#L14) to [addListeners()](https://github.com/Andre601/PowerSuggestionBot/blob/master/src/main/java/core/Main.java#L82) in Main.java and if yes, how (gives a error...)

I'm glad for every help.
(Also please don't judge me to hard for my choice of code "design"... It's my first try on a Bot.)

**Comment by Andre601** [comment]
After some investigation does it look like, that it was a simple Export-error (dependencies wasn't exported correctly)
But now is the issue, that the bot doesn't play/join the channel, when I run the command, to add a video...

**Comment by Andre601** [comment]
I tested around and found out, that it doesn't read the text after "play" in the command...

It always has a empty string, which of course explains, why it doesn't find the music.

**Comment by CorruptComputer** [comment]
This isn't really an issue with lavaplayer and I would suggest to close this issue. If you want a reference for some working code you can use this: https://github.com/CorruptComputer/Officer-Beepsky 

Also if you'd like I don't mind taking a look through your code and giving some tips tonight, you can add me on Discord with `CorruptComputer#9473`!
