### ISSUE TITLE
Youtube region restriction

### ISSUE THREAD

**Issue by taylor224** [sedmelluq/lavaplayer#9]
Hello,

First, Thank you for made lavaplayer.
I am using lavaplayer well, but having some issue about Youtube region restriction. For example, [this video](https://www.youtube.com/watch?v=VmW95iLIxSw) cannot play outside of South Korea and Japan. The server that using lavaplayer is in Japan but It is not working with following error message.
```This video contains content from PONYCANYON, who has blocked it in your country on copyright grounds.```

What should I do for play video like this?
Thank you.

**Comment by Frederikam** [comment]
I don't think youtube will provide the video as long as you are connecting from within a restricted region. I think the only solution would be to use a proxy.

**Comment by taylor224** [comment]
Sorry, It is my misunderstanding about Youtube region restriction.
The playable region of that video is only South Korea, not Japan. So cannot play in Japan.
