### ISSUE TITLE
AudioPlayer won't play some tracks from YouTube.

### ISSUE THREAD

**Issue by justincenteno99** [sedmelluq/lavaplayer#94]
This only happened about recently when my friends tried to play a song and nothing came out of the bot. The code I used should be correct and I made sure I got the updated lavaplayer as well.

**Comment by sedmelluq** [comment]
Please provide:

- Link to the specific track.
- Lavaplayer logs when trying to play the track.

**Comment by justincenteno99** [comment]
`[07:38:54] [Info] [JDA]: Login Successful!
[07:38:54] [Info] [JDASocket]: Connected to WebSocket
[07:38:55] [Info] [JDA]: Finished Loading!
log4j:WARN No appenders could be found for logger (com.sedmelluq.discord.lavaplayer.tools.io.TrustManagerBuilder).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[07:39:13] [Info] [JDAAudioManager]: Audio System successfully setup!`

and it's not just one track, it's multiple.
Example is https://www.youtube.com/watch?v=3BXDsVD6O10

**Comment by shikhir-arora** [comment]
I'm not able to reproduce the issue with `1.2.51` here -- can play that track fine.

**Comment by justincenteno99** [comment]
I have to say thanks!

I did some testing and I was using `1.2.9`, so I tried `1.2.51` and it seemed like it worked beautifully.
Mark this as closed
