### ISSUE TITLE
Robot loop enters & out the voice channel 

### ISSUE THREAD

**Issue by cocomine** [sedmelluq/lavaplayer#97]
When I type play commands robot will have this problem

Code: https://github.com/cocomine/PlayerDeath

Voide: https://drive.google.com/file/d/19XKcRoG-OYbixa23UUJ_wqvnirOHBAmK/view?usp=sharing

**Comment by LordAll** [comment]
I have the same problem, but I don't know why, before my music run correctly

**Comment by Dot-Rar** [comment]
As a temporary fix, change your discord voice region

**Comment by LordAll** [comment]
Ok, thank you !

**Comment by cocomine** [comment]
ok, I try

**Comment by LordAll** [comment]
It's okey for me !

**Comment by Dot-Rar** [comment]
According to ducc (dabBot dev), it's a Discord issue, not one with LavaPlayer. If this is the case, you should probably close the issue since it is outside of sedmelluq's hands.

**Comment by cocomine** [comment]
Not work for me :(
Is change Voice Server Region?

I run well on a local computer test
But when I put on the hosting server there is a problem

**Comment by sedmelluq** [comment]
Closing as this discussion is no longer active and was not relevant in the first place.
